import assert from "node:assert/strict";
import test from "node:test";
import { allocateNextIssueReference, assignRecordToIssue, createCaseIssue, deleteCaseIssue, getIssueDisplayLabel, HUMAN_READABLE_ISSUE_PROMPT, mergeCaseIssues, normalizeCaseIssues, removeRecordFromIssue, renameCaseIssue, resolveCaseIssue, updateCaseIssue } from "./issueDomain.js";

const oldCase = { id: "case-1", createdAt: "2026-01-01T00:00:00Z", incidents: [{ id: "i1", sequenceGroup: "Heating" }], evidence: [{ id: "e1", sequenceGroup: " Heating " }], documents: [], ledger: [], strategy: [], watchItems: [], parties: [{ id: "p1", name: "Owner" }] };
const migrate = () => normalizeCaseIssues(oldCase, { sequenceGroupMeta: { Heating: { description: "Legacy description", updatedAt: "2026-02-01T00:00:00Z" }, Empty: { description: "Empty issue" } } });

test("legacy and metadata-only groups migrate deterministically with assignments", () => { const result = migrate(); assert.equal(result.caseData.issues.length, 2); assert.deepEqual(result.caseData.issues.map((x) => x.reference), ["ISS-001", "ISS-002"]); assert.equal(result.caseData.evidence[0].sequenceGroupId, result.caseData.incidents[0].sequenceGroupId); assert.equal(result.caseData.issues.find((x) => x.name === "Heating").description, "Legacy description"); });
test("migration is idempotent and does not rewrite identity or timestamps", () => { const first = migrate().caseData; const second = normalizeCaseIssues(first).caseData; assert.strictEqual(second, first); assert.deepEqual(second, first); });
test("migration does not mutate source input", () => { const before = structuredClone(oldCase); migrate(); assert.deepEqual(oldCase, before); });
test("display labels combine reference and editable name", () => assert.equal(getIssueDisplayLabel({ reference: "ISS-003", name: "Heating" }), "ISS-003 — Heating"));
test("create applies required defaults and monotonic identity", () => { const base = migrate().caseData; const result = createCaseIssue(base, { name: "Repairs" }, { now: "2026-03-01T00:00:00Z" }); assert.equal(result.success, true); assert.equal(result.issue.reference, "ISS-003"); assert.equal(result.issue.status, "open"); assert.equal(result.issue.priority, "normal"); assert.match(result.issue.id, /^issue_/); });
test("duplicate normalized names are blocked", () => assert.equal(createCaseIssue(migrate().caseData, { name: " heating " }).success, false));
test("ID and reference are immutable while metadata validates", () => { const base = migrate().caseData; const issue = base.issues[0]; assert.equal(updateCaseIssue(base, issue.id, { id: "changed" }).success, false); assert.equal(updateCaseIssue(base, issue.id, { status: "invented" }).success, false); assert.equal(updateCaseIssue(base, issue.id, { priority: "urgent" }).success, false); assert.equal(updateCaseIssue(base, issue.id, { ownerPartyId: "missing" }).success, false); });
test("metadata update stores owner date position and timestamp", () => { const base = migrate().caseData; const issue = base.issues[0]; const result = updateCaseIssue(base, issue.id, { status: "monitoring", priority: "high", ownerPartyId: "p1", reviewDate: "2026-08-15", currentPosition: "Awaiting response", purpose: "Track repairs" }, { now: "2026-08-01T00:00:00Z" }); assert.equal(result.success, true); assert.equal(result.issue.ownerPartyId, "p1"); assert.equal(result.issue.updatedAt, "2026-08-01T00:00:00Z"); });
test("rename preserves ID/reference and synchronizes compatibility labels", () => { const base = migrate().caseData; const issue = resolveCaseIssue(base, "Heating"); const result = renameCaseIssue(base, issue.id, "Winter Heating", { now: "2026-08-01T00:00:00Z" }); assert.equal(result.issue.id, issue.id); assert.equal(result.issue.reference, issue.reference); assert.equal(result.caseData.incidents[0].sequenceGroup, "Winter Heating"); assert.equal(result.caseData.incidents[0].sequenceGroupId, issue.id); });
test("resolution prioritizes ID then reference then unique normalized name", () => { const base = migrate().caseData; const issue = base.issues[0]; assert.equal(resolveCaseIssue(base, { issueId: issue.id }).id, issue.id); assert.equal(resolveCaseIssue(base, { issueReference: issue.reference }).id, issue.id); assert.equal(resolveCaseIssue(base, { issueName: ` ${issue.name.toUpperCase()} ` }).id, issue.id); });
test("duplicate IDs and references are rejected as migration conflicts", () => { const base = migrate().caseData; const duplicate = { ...base, issues: [...base.issues, { ...base.issues[0], name: "Other" }] }; const result = normalizeCaseIssues(duplicate); assert.equal(result.changed, false); assert.ok(result.conflicts.some((x) => x.code === "duplicate_issue_id")); assert.ok(result.conflicts.some((x) => x.code === "duplicate_issue_reference")); });
test("assignment by ID synchronizes name and removal clears both fields", () => { const base = { ...migrate().caseData, documents: [{ id: "d1" }] }; const issue = base.issues[0]; const assigned = assignRecordToIssue(base, "documents", "d1", issue.id); assert.equal(assigned.caseData.documents[0].sequenceGroup, issue.name); const removed = removeRecordFromIssue(assigned.caseData, "documents", "d1"); assert.equal(removed.caseData.documents[0].sequenceGroupId, ""); assert.equal(removed.caseData.documents[0].sequenceGroup, ""); });
test("merge preserves destination identity and retires source reference", () => { const base = migrate().caseData; const source = resolveCaseIssue(base, "Heating"); const destination = resolveCaseIssue(base, "Empty"); const result = mergeCaseIssues(base, source.id, destination.id, { now: "2026-08-01" }); assert.equal(result.caseData.incidents[0].sequenceGroupId, destination.id); assert.ok(result.caseData.retiredIssueReferences.includes(source.reference)); assert.equal(resolveCaseIssue(result.caseData, { issueId: source.id }), null); });
test("delete preserves records, clears assignment, and prevents reference reuse", () => { const base = migrate().caseData; const issue = resolveCaseIssue(base, "Heating"); const result = deleteCaseIssue(base, issue.id, { now: "2026-08-01" }); assert.equal(result.caseData.incidents.length, 1); assert.equal(result.caseData.incidents[0].sequenceGroup, ""); assert.ok(result.caseData.retiredIssueReferences.includes(issue.reference)); assert.notEqual(allocateNextIssueReference(result.caseData).reference, issue.reference); });
test("GPT policy requires human references and restricts internal IDs", () => { assert.match(HUMAN_READABLE_ISSUE_PROMPT, /ISS-003 — Heating Failure/); assert.match(HUMAN_READABLE_ISSUE_PROMPT, /Do not refer.*internal UUID/); });
