import { formatReportDate } from "./reportArticleHelpers.js";
import { ReportLinkedList } from "./ReportArticleShared.jsx";

export default function CaseBundleReportArticle({ report, className = "" }) {
  if (!report) return null;

  const sectionClass = "break-before-page border-b border-neutral-200 py-7 print:break-before-page print:py-6 first:break-before-auto";
  const diagnostics = report.sections.combinedDiagnostics;

  return (
    <article className={className}>
      <header className="border-b border-neutral-200 pb-6 print:pb-5">
        <div className="text-xs font-bold uppercase tracking-[0.18em] text-neutral-500">CASE BUNDLE REPORT</div>
        <div className="mt-2 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <h1 className="text-3xl font-bold leading-tight text-neutral-950 print:text-[22pt]">{report.title}</h1>
            <div className="mt-3 grid gap-1 text-sm text-neutral-600">
              <div><span className="font-semibold text-neutral-950">Case:</span> {report.caseOverview.name || report.sourceCaseId || "Untitled Case"}</div>
              <div><span className="font-semibold text-neutral-950">Scope:</span> {report.scopeLabel}</div>
              <div><span className="font-semibold text-neutral-950">Generated:</span> {formatReportDate(report.generatedAt)}</div>
            </div>
          </div>
          <div className="rounded-lg border border-neutral-200 bg-neutral-50 px-3 py-2 text-sm text-neutral-600 print:bg-white">
            <div><span className="font-semibold text-neutral-900">Audience:</span> {report.audience}</div>
            <div><span className="font-semibold text-neutral-900">Generated by:</span> {report.generationMetadata.generatedBy}</div>
            <div><span className="font-semibold text-neutral-900">Sections:</span> {report.generationMetadata.sectionCount}</div>
          </div>
        </div>
      </header>

      <section className="border-b border-neutral-200 py-6 print:py-5">
        <h2 className="text-sm font-bold uppercase tracking-wider text-neutral-500">Bundle Contents</h2>
        <div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">
          {report.contentsSummary.map((item) => (
            <div key={item.key} className="rounded-lg border border-neutral-200 p-3">
              <div className="flex items-center justify-between gap-3">
                <div className="text-sm font-semibold text-neutral-950">{item.label}</div>
                <span className={`rounded border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider ${item.included ? "border-lime-200 bg-lime-50 text-lime-800" : "border-neutral-200 bg-neutral-50 text-neutral-500"}`}>
                  {item.included ? "Included" : item.selected ? "Unavailable" : "Off"}
                </span>
              </div>
              <div className="mt-2 text-sm text-neutral-600">Items: {item.itemCount}</div>
              {item.unavailableReason ? <div className="mt-1 text-xs text-amber-700">{item.unavailableReason}</div> : null}
            </div>
          ))}
        </div>
      </section>

      {report.sections.threadIssue && (
        <section className={sectionClass}>
          <h2 className="text-sm font-bold uppercase tracking-wider text-neutral-500">Thread / Issue Report</h2>
          <p className="mt-2 text-sm text-neutral-700">{report.sections.threadIssue.scopeSummary}</p>
          <div className="mt-4 grid gap-3 sm:grid-cols-4">
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Incidents: <span className="font-semibold">{report.sections.threadIssue.threadSummary.incidentCount}</span></div>
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Evidence: <span className="font-semibold">{report.sections.threadIssue.threadSummary.evidenceCount}</span></div>
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Documents: <span className="font-semibold">{report.sections.threadIssue.threadSummary.documentCount}</span></div>
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Ledger: <span className="font-semibold">{report.sections.threadIssue.threadSummary.ledgerCount}</span></div>
          </div>
        </section>
      )}

      {report.sections.evidencePack && (
        <section className={sectionClass}>
          <h2 className="text-sm font-bold uppercase tracking-wider text-neutral-500">Evidence Pack</h2>
          <div className="mt-4 space-y-2">
            {report.sections.evidencePack.evidenceMatrix.slice(0, 12).map((item) => (
              <div key={item.id} className="break-inside-avoid rounded-lg border border-neutral-200 p-3 print:break-inside-avoid">
                <div className="font-semibold text-neutral-950">{item.title}</div>
                <div className="mt-1 text-sm text-neutral-700">{item.functionSummary || "Missing functionSummary"}</div>
                <div className="mt-1 text-xs text-neutral-500">Linked incidents: <ReportLinkedList items={item.linkedIncidents} /></div>
              </div>
            ))}
          </div>
        </section>
      )}

      {report.sections.documentPack && (
        <section className={sectionClass}>
          <h2 className="text-sm font-bold uppercase tracking-wider text-neutral-500">Document Pack</h2>
          <div className="mt-4 space-y-2">
            {report.sections.documentPack.documentMatrix.slice(0, 12).map((item) => (
              <div key={item.id} className="break-inside-avoid rounded-lg border border-neutral-200 p-3 print:break-inside-avoid">
                <div className="font-semibold text-neutral-950">{item.title}</div>
                <div className="mt-1 text-sm text-neutral-700">{item.summary || item.textExcerpt || "No summary recorded."}</div>
                <div className="mt-1 text-xs text-neutral-500">Linked records: <ReportLinkedList items={item.linkedRecords} /></div>
              </div>
            ))}
          </div>
        </section>
      )}

      {report.sections.ledgerPack && (
        <section className={sectionClass}>
          <h2 className="text-sm font-bold uppercase tracking-wider text-neutral-500">Ledger Pack</h2>
          <div className="mt-4 grid gap-3 sm:grid-cols-4">
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Entries: <span className="font-semibold">{report.sections.ledgerPack.atAGlance.totalEntryCount}</span></div>
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Total: <span className="font-semibold">{report.sections.ledgerPack.atAGlance.totalAmount}</span></div>
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">With proof: <span className="font-semibold">{report.sections.ledgerPack.atAGlance.entriesWithProofCount}</span></div>
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Missing proof: <span className="font-semibold">{report.sections.ledgerPack.atAGlance.entriesWithoutProofCount}</span></div>
          </div>
        </section>
      )}

      {report.sections.strategyActions && (
        <section className={sectionClass}>
          <h2 className="text-sm font-bold uppercase tracking-wider text-neutral-500">Strategy / Actions Summary</h2>
          <div className="mt-4 grid gap-4 md:grid-cols-2">
            <div>
              <h3 className="text-sm font-semibold text-neutral-950">Strategy Records</h3>
              {report.sections.strategyActions.strategyRecords.length === 0 ? <p className="mt-2 text-sm text-neutral-600">No strategy records included.</p> : (
                <ul className="mt-2 space-y-2 text-sm leading-6 text-neutral-700">
                  {report.sections.strategyActions.strategyRecords.map((item) => <li key={item.id}>- {item.title}</li>)}
                </ul>
              )}
            </div>
            <div>
              <h3 className="text-sm font-semibold text-neutral-950">Next Actions</h3>
              {report.sections.strategyActions.actionSummary.nextActions.length === 0 ? <p className="mt-2 text-sm text-neutral-600">No scoped next actions.</p> : (
                <ul className="mt-2 space-y-2 text-sm leading-6 text-neutral-700">
                  {report.sections.strategyActions.actionSummary.nextActions.map((item, index) => <li key={`${item}-${index}`}>- {item}</li>)}
                </ul>
              )}
            </div>
          </div>
        </section>
      )}

      {diagnostics && (
        <section className="break-before-page py-7 print:break-before-page print:py-6">
          <h2 className="text-sm font-bold uppercase tracking-wider text-neutral-500">Combined Diagnostics</h2>
          <div className="mt-4 grid gap-3 sm:grid-cols-4">
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Broken links: <span className="font-semibold">{diagnostics.brokenLinks.length}</span></div>
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Orphans: <span className="font-semibold">{diagnostics.orphanRecords.length}</span></div>
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Weak links: <span className="font-semibold">{diagnostics.weaklyLinkedRecords.length}</span></div>
            <div className="rounded-lg border border-neutral-200 p-3 text-sm">Unsupported incidents: <span className="font-semibold">{diagnostics.unsupportedIncidents.length}</span></div>
          </div>
          {[...diagnostics.warnings, ...diagnostics.suggestions].length > 0 ? (
            <ul className="mt-4 space-y-2 text-sm leading-6 text-neutral-700">
              {[...diagnostics.warnings, ...diagnostics.suggestions].slice(0, 12).map((item, index) => (
                <li key={`${item.id || "diagnostic"}-${index}`}>- {item.message}</li>
              ))}
            </ul>
          ) : null}
        </section>
      )}
    </article>
  );
}
