import { getReportDocumentSection } from "../../report/reportDocument.js";

const TYPE_LABELS = { incident: "Incident", evidence: "Evidence", document: "Document", ledger: "Ledger", strategy: "Strategy", watch: "To Watch" };
function dateLabel(entry) { if (entry.dateStatus === "malformed") return `Malformed: ${entry.originalDate || entry.date || "unknown"}`; if (entry.dateStatus === "missing") return "Missing date"; return entry.date; }

export default function ChronologyReportArticle({ reportDocument, className = "" }) {
  const summary = reportDocument?.summary || {};
  const groups = getReportDocumentSection(reportDocument, "chronology")?.groups || [];
  const totals = getReportDocumentSection(reportDocument, "record-type-totals")?.metadata || {};
  return (
    <article className={className} data-report-document="chronologyReport">
      <header className="border-b border-neutral-200 pb-5 dark:border-neutral-700"><p className="text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">Complete factual report</p><h2 className="mt-1 text-2xl font-bold text-neutral-950 dark:text-neutral-50">{reportDocument?.report?.title || "Chronology Report"}</h2><p className="mt-2 text-sm text-neutral-600 dark:text-neutral-300">{summary.scopeLabel || "Whole case"} · Source revision {reportDocument?.source?.sourceRevision?.fingerprint || "unavailable"}</p></header>
      <section aria-labelledby="chronology-summary-heading" className="mt-6"><h3 id="chronology-summary-heading" className="text-lg font-bold text-neutral-900 dark:text-neutral-100">Summary</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Entries", summary.totalChronologyEntries], ["Valid dates", summary.validDateCount], ["Malformed dates", summary.malformedDateCount], ["Missing dates", summary.missingDateCount]].map(([label, value]) => <div key={label} className="rounded-lg border border-neutral-200 p-3 dark:border-neutral-700"><dt className="text-xs font-semibold text-neutral-500 dark:text-neutral-400">{label}</dt><dd className="mt-1 text-xl font-bold text-neutral-900 dark:text-neutral-100">{value || 0}</dd></div>)}</dl></section>
      <section aria-labelledby="record-type-totals-heading" className="mt-7"><h3 id="record-type-totals-heading" className="text-lg font-bold text-neutral-900 dark:text-neutral-100">Record Type Totals</h3><dl className="mt-2 flex flex-wrap gap-x-5 gap-y-2 text-sm">{Object.entries(TYPE_LABELS).map(([type, label]) => <div key={type}><dt className="inline font-semibold">{label}: </dt><dd className="inline">{totals[type] || 0}</dd></div>)}</dl></section>
      <section aria-labelledby="chronology-heading" className="mt-7"><h3 id="chronology-heading" className="text-lg font-bold text-neutral-900 dark:text-neutral-100">Chronology</h3>{!groups.length ? <p className="mt-3 rounded-lg border border-dashed border-neutral-300 p-4 text-sm text-neutral-600 dark:border-neutral-700 dark:text-neutral-300">No records are included in this chronology scope.</p> : <div className="mt-4 space-y-7">{groups.map((group) => <section key={group.id} aria-labelledby={`${group.id}-heading`} className="break-inside-avoid"><h4 id={`${group.id}-heading`} className="border-b border-neutral-200 pb-2 text-base font-bold text-neutral-900 dark:border-neutral-700 dark:text-neutral-100">{group.label}</h4><ol className="mt-3 space-y-3">{group.entries.map((entry) => <li key={`${entry.recordType}:${entry.recordId}`} className="border-l-2 border-burgundy-700 pl-4"><time className="text-xs font-bold text-neutral-500 dark:text-neutral-400">{dateLabel(entry)}</time><p className="mt-1 text-sm font-bold text-neutral-900 dark:text-neutral-100">{TYPE_LABELS[entry.recordType] || entry.recordType} · {entry.recordId} · {entry.title}</p>{entry.summary ? <p className="mt-1 whitespace-pre-wrap text-sm text-neutral-600 dark:text-neutral-300">{entry.summary}</p> : null}<p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400">{entry.sequenceGroup ? `Sequence Group: ${entry.sequenceGroup}` : "Ungrouped"} · {entry.linkedRecordCount} linked record(s) · {entry.attachmentCount} attachment(s){entry.archived ? " · Archived" : ""}</p>{entry.resolvedPartyNames?.length ? <p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400">Parties: {entry.resolvedPartyNames.join(", ")}</p> : null}</li>)}</ol></section>)}</div>}</section>
      <section aria-labelledby="chronology-notices-heading" className="mt-7 border-t border-neutral-200 pt-5 dark:border-neutral-700"><h3 id="chronology-notices-heading" className="text-lg font-bold text-neutral-900 dark:text-neutral-100">Notices</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-neutral-600 dark:text-neutral-300">{(reportDocument?.notices || []).map((notice) => <li key={notice.code}>{notice.message}</li>)}</ul></section>
    </article>
  );
}
