import { ReportDocumentAppendix, ReportDocumentCallout, ReportDocumentControl, ReportDocumentFooter, ReportDocumentHeader, ReportDocumentSection, ReportDocumentShell, ReportDocumentStatistics } from "./document/index.js";
function section(document, id) { return (document?.sections || []).find((item) => item.id === id) || {}; }
function human(value) { return String(value || "Not recorded").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function SourceLabel({ source }) { const label = source === "ai_assisted" ? "AI-assisted commentary — not automatically verified" : source === "user_authored" ? "User-authored case position" : "Structured case data"; return <p className="mb-2 text-xs font-bold text-neutral-500 dark:text-neutral-400 print:text-neutral-700">Source: {label}</p>; }
function List({ items = [], empty = "None recorded." }) { return items.length ? <ul className="space-y-2">{items.map((item, index) => <li key={item.id || item.recordId || `${String(item.title || item.message || item)}-${index}`} className="break-inside-avoid border-l-2 border-neutral-300 pl-3 dark:border-neutral-600 print:border-black">{item.message || item.action || item.title || String(item)}{item.issueLabel ? <span className="block text-xs text-neutral-500 dark:text-neutral-400">{item.issueLabel}</span> : null}</li>)}</ul> : <p className="text-sm text-neutral-600 dark:text-neutral-300">{empty}</p>; }
function Issues({ items = [] }) { return items.length ? <div className="space-y-5">{items.map((issue) => <section key={issue.displayLabel} className="break-inside-avoid border-t border-neutral-300 pt-4 first:border-0 first:pt-0 dark:border-neutral-600"><h3 className="text-lg font-semibold">{issue.displayLabel}</h3><p className="mt-1 text-sm">{issue.purpose || "No Issue purpose is recorded."}</p><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="font-semibold">Status</dt><dd>{human(issue.status)}</dd></div><div><dt className="font-semibold">Priority</dt><dd>{human(issue.priority)}</dd></div><div><dt className="font-semibold">Owner</dt><dd>{issue.owner || "Not recorded"}</dd></div><div><dt className="font-semibold">Review date</dt><dd>{issue.reviewDate || "Not recorded"}</dd></div></dl>{issue.currentPosition ? <div className="mt-3"><SourceLabel source="user_authored"/><p>{issue.currentPosition}</p></div> : null}{issue.narrative ? <ReportDocumentCallout variant="information" title="AI-assisted explanation"><SourceLabel source="ai_assisted"/><p>{issue.narrative.whatHappened}</p><List items={issue.narrative.explanation} /></ReportDocumentCallout> : null}<div className="mt-3"><p className="text-xs font-semibold">Readable supporting references</p><List items={issue.recordReferences} empty="No directly assigned supporting records are listed." /></div></section>)}</div> : <p className="text-sm text-neutral-600 dark:text-neutral-300">No Issues are recorded. This whole-case summary remains available without Issue organisation.</p>; }
function Appendix({ appendix }) { if (appendix.groups) return <div className="space-y-4">{appendix.groups.map((group) => <section key={group.id}><h3 className="font-semibold">{group.label}</h3><List items={(group.entries || []).map((entry) => ({ ...entry, title: `${entry.date || human(entry.dateStatus)} — ${entry.title}` }))}/></section>)}</div>; return <List items={appendix.items || []}/>; }
export default function ClientReportArticle({ reportDocument }) {
  if (!reportDocument) return null; const p = reportDocument.presentation || {}; const meta = reportDocument.narrativeMetadata || {}; const notice = section(reportDocument, "important-notice"); const glance = section(reportDocument, "at-a-glance"); const situation = section(reportDocument, "current-situation"); const issues = section(reportDocument, "main-issues"); const chronology = section(reportDocument, "chronology"); const material = section(reportDocument, "supporting-material"); const position = section(reportDocument, "recorded-position"); const outstanding = section(reportDocument, "outstanding-matters"); const next = section(reportDocument, "next-steps"); const limits = section(reportDocument, "limitations");
  const header = <ReportDocumentHeader title="Client Report" subtitle="A plain-language summary of the recorded case position" caseName={reportDocument.source?.caseName} generatedAt={reportDocument.report?.generatedAt} version={p.version} documentStatus={p.documentStatus} confidentiality={p.confidentiality} preparedBy={p.preparedBy} approvedBy={p.approvedBy}/>; const control = <ReportDocumentControl purpose={p.purpose} audience={p.audience} scope={p.scope} exclusions={p.exclusions} completeness={p.completeness} generatedAt={reportDocument.report?.generatedAt} sourceRevision={reportDocument.source?.sourceRevision?.fingerprint} version={p.version} documentStatus={p.documentStatus} confidentiality={p.confidentiality} aiAssistance={p.aiAssistance}/>; const footer = <ReportDocumentFooter reportTitle="Client Report" caseName={reportDocument.source?.caseName} sourceRevision={reportDocument.source?.sourceRevision?.fingerprint} version={p.version} documentStatus={p.documentStatus} confidentiality={p.confidentiality} generatedAt={reportDocument.report?.generatedAt}/>;
  return <ReportDocumentShell aria-label="Client Report" header={header} documentControl={control} footer={footer}>
    <ReportDocumentCallout variant="warning" title="AI-assisted draft"><p>{notice.text}</p><p className="mt-2 font-semibold">Human review: {meta.reviewed ? `Recorded${meta.reviewedBy ? ` by ${meta.reviewedBy}` : ""}` : "Not recorded"}. Approval: {meta.approved ? `Recorded${meta.approvedBy ? ` by ${meta.approvedBy}` : ""}` : "Not recorded"}.</p></ReportDocumentCallout>
    {meta.revisionState !== "current" ? <ReportDocumentCallout variant="limitation" title={meta.revisionState === "stale" ? "Stale AI-assisted draft" : "Narrative provenance unknown"}>{meta.revisionState === "stale" ? "The case has changed since this narrative was generated. Regenerate or review it carefully before sharing." : "This legacy narrative has no recorded source revision, so it cannot be confirmed against the current case state."}</ReportDocumentCallout> : null}
    <ReportDocumentSection id="at-a-glance" title="At a Glance"><SourceLabel source="structured"/><ReportDocumentStatistics columns={4} items={Object.entries(glance.metadata || {}).map(([key, value]) => ({ key, label: human(key.replace(/([A-Z])/g, " $1")), value }))}/>{glance.narrative ? <div className="mt-4"><SourceLabel source="ai_assisted"/><List items={glance.narrative.items}/></div> : null}</ReportDocumentSection>
    <ReportDocumentSection id="current-situation" title="Your Current Situation"><SourceLabel source="structured"/><p>Recorded case status: {human(situation.structured?.caseStatus)}</p>{situation.userAuthored?.items?.length ? <div><SourceLabel source="user_authored"/><List items={situation.userAuthored.items.map((item) => ({ title: item.currentPosition, issueLabel: item.issueLabel }))}/></div> : null}{situation.aiAssisted ? <ReportDocumentCallout variant="information" title="AI-assisted plain-language explanation"><SourceLabel source="ai_assisted"/><p>{situation.aiAssisted.text}</p></ReportDocumentCallout> : null}</ReportDocumentSection>
    <ReportDocumentSection id="main-issues" title="Main Issues"><Issues items={issues.items}/></ReportDocumentSection>
    <ReportDocumentSection id="chronology" title="What Has Happened" description="A concise canonical chronology; malformed and missing dates remain separately labelled.">{(chronology.groups || []).length ? chronology.groups.map((group) => <section key={group.id}><h3 className="text-lg font-semibold">{group.label}</h3><List items={(group.entries || []).map((entry) => ({ ...entry, title: `${entry.date || human(entry.dateStatus)} — ${entry.title}` }))}/></section>) : <p>No chronology entries are recorded.</p>}</ReportDocumentSection>
    <ReportDocumentSection id="supporting-material" title="Evidence and Documents" description="Recorded supporting material; inclusion does not establish authenticity or legal sufficiency."><SourceLabel source="structured"/><ReportDocumentStatistics columns={3} items={Object.entries(material.metadata || {}).map(([key, value]) => ({ key, label: human(key.replace(/([A-Z])/g, " $1")), value }))}/><List items={material.items}/></ReportDocumentSection>
    <ReportDocumentSection id="recorded-position" title="Current Recorded Position"><SourceLabel source="structured"/><List items={position.structured?.observations}/>{position.userAuthored?.items?.length ? <div><SourceLabel source="user_authored"/><List items={position.userAuthored.items.map((item) => ({ title: item.text, issueLabel: item.issueLabel }))}/></div> : null}{position.aiAssisted ? <ReportDocumentCallout variant="information" title="Reviewed explanatory commentary required"><SourceLabel source="ai_assisted"/><List items={position.aiAssisted.items}/></ReportDocumentCallout> : null}</ReportDocumentSection>
    <ReportDocumentSection id="outstanding-matters" title="Outstanding Matters"><SourceLabel source="structured"/><List items={outstanding.items} empty="No warning or critical structured findings are currently recorded. This is not a finding of factual or legal completeness."/></ReportDocumentSection>
    <ReportDocumentSection id="next-steps" title="Next Steps"><SourceLabel source="structured"/><List items={next.items} empty="No structured Issue, Strategy, or Watch actions are currently recorded."/></ReportDocumentSection>
    <ReportDocumentSection id="limitations" title="Important Limitations"><List items={limits.items}/></ReportDocumentSection>
    {(reportDocument.appendices || []).map((appendix) => <ReportDocumentAppendix key={appendix.id} id={appendix.id} label={appendix.label} title={appendix.title}><Appendix appendix={appendix}/></ReportDocumentAppendix>)}
  </ReportDocumentShell>;
}
