import {
  ReportDocumentAppendix, ReportDocumentCallout, ReportDocumentControl, ReportDocumentFooter,
  ReportDocumentHeader, ReportDocumentSection, ReportDocumentShell, ReportDocumentStatistics,
} from "./document/index.js";

const TYPE_LABELS = { incident: "Incident", evidence: "Evidence", document: "Document", ledger: "Ledger", strategy: "Strategy", watch: "To Watch" };
function getSection(document, id) { return (document?.sections || []).find((item) => item.id === id) || {}; }
function display(value, fallback = "Not recorded") { return value === null || value === undefined || value === "" ? fallback : String(value); }
function humanStatus(value) { return String(value || "Not recorded").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

function SimpleList({ items = [], empty }) {
  return items.length ? <ul className="space-y-2">{items.map((item, index) => <li key={item.id || `${item.code || item.title || "item"}-${index}`} className="break-inside-avoid border-l-2 border-neutral-300 pl-3 dark:border-neutral-600 print:border-black">{item.text || item.message || item.title || String(item)}</li>)}</ul> : <p className="text-sm text-neutral-600 dark:text-neutral-300">{empty}</p>;
}

function ChronologyGroups({ groups = [] }) {
  if (!groups.length) return <p className="text-sm text-neutral-600 dark:text-neutral-300">No dated investigation records are available in this scope.</p>;
  return <div className="space-y-6">{groups.map((group) => <section key={group.id} aria-labelledby={`${group.id}-investigation-heading`}><h3 id={`${group.id}-investigation-heading`} className="text-lg font-semibold text-neutral-900 dark:text-neutral-100 print:text-black">{group.label}</h3><ol className="mt-3 space-y-3">{(group.entries || []).map((entry) => <li key={`${entry.recordType}:${entry.recordId}`} className="break-inside-avoid border-l-2 border-burgundy-700 pl-4 print:border-black"><time className="text-xs font-semibold text-neutral-500 dark:text-neutral-400 print:text-neutral-700">{entry.dateStatus === "valid" ? entry.date : entry.dateStatus === "malformed" ? `Malformed date: ${entry.originalDate || entry.date || "unknown"}` : "Missing date"}</time><p className="mt-1 break-words font-semibold text-neutral-950 dark:text-neutral-50 print:text-black">{TYPE_LABELS[entry.recordType] || entry.recordType}: {entry.title}</p>{entry.summary ? <p className="mt-1 whitespace-pre-wrap text-sm text-neutral-600 dark:text-neutral-300 print:text-neutral-800">{entry.summary}</p> : null}{entry.resolvedPartyNames?.length ? <p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400 print:text-neutral-700">People: {entry.resolvedPartyNames.join(", ")}</p> : null}</li>)}</ol></section>)}</div>;
}

function CompactRecords({ items = [], kind }) {
  if (!items.length) return <p className="text-sm text-neutral-600 dark:text-neutral-300">No {kind} are recorded in this scope. This absence does not determine the merits of the investigation.</p>;
  return <ul className="grid gap-3 sm:grid-cols-2">{items.map((item) => <li key={item.id} className="break-inside-avoid rounded-lg border border-neutral-200 p-3 dark:border-neutral-700 print:rounded-none print:border-neutral-400"><p className="break-words font-semibold text-neutral-950 dark:text-neutral-50 print:text-black">{item.title}</p>{item.functionSummary || item.summary ? <p className="mt-1 text-sm leading-6 text-neutral-600 dark:text-neutral-300 print:text-neutral-800">{item.functionSummary || item.summary}</p> : null}{item.verificationState || item.category ? <p className="mt-2 text-xs text-neutral-500 dark:text-neutral-400 print:text-neutral-700">{item.verificationState || item.category}</p> : null}</li>)}</ul>;
}

function AppendixTable({ appendix }) {
  const rows = appendix.rows || [];
  if (!rows.length) return <p>No records are included.</p>;
  if (appendix.type === "incident-schedule") return <table className="proveit-report-wide-table w-full table-fixed border-collapse text-left text-xs"><caption className="sr-only">Complete Incident Schedule</caption><thead><tr>{["Incident", "Date", "Status", "Issue", "Evidence"].map((label) => <th key={label} scope="col" className="border-b border-neutral-500 p-2">{label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.incidentId} className="align-top"><td className="break-words border-b p-2"><strong>{row.title}</strong><br /><span className="font-mono text-[10px]">{row.incidentId}</span></td><td className="break-words border-b p-2">{display(row.canonicalDate, row.dateStatus)}</td><td className="break-words border-b p-2">{display(row.status)}</td><td className="break-words border-b p-2">{display(row.sequenceGroup, "Ungrouped")}</td><td className="break-words border-b p-2">{row.linkedEvidence?.map((item) => item.title).join(", ") || "None"}</td></tr>)}</tbody></table>;
  const idKey = appendix.type === "evidence-schedule" ? "evidenceId" : appendix.type === "document-schedule" ? "documentId" : "ledgerId";
  return <table className="proveit-report-wide-table w-full table-fixed border-collapse text-left text-xs"><caption className="sr-only">{appendix.title}</caption><thead><tr>{["Record", "Date", "Status", "Details"].map((label) => <th key={label} scope="col" className="border-b border-neutral-500 p-2">{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row[idKey] || index} className="align-top"><td className="break-words border-b p-2"><strong>{row.title}</strong><br /><span className="font-mono text-[10px]">{row[idKey]}</span></td><td className="break-words border-b p-2">{display(row.date || row.documentDate)}</td><td className="break-words border-b p-2">{display(row.status || row.verificationState || row.proofStatus)}</td><td className="break-words border-b p-2">{display(row.functionSummary || row.summary || row.notes || row.amount)}</td></tr>)}</tbody></table>;
}

export default function InvestigationReportArticle({ reportDocument, className = "" }) {
  if (!reportDocument) return null;
  const summary = reportDocument.summary || {};
  const presentation = reportDocument.presentation || {};
  const issue = summary.issue;
  const current = getSection(reportDocument, "current-position").metadata || {};
  const statistics = getSection(reportDocument, "snapshot").metadata || {};
  const findings = getSection(reportDocument, "key-findings").items || [];
  const chronology = getSection(reportDocument, "narrative-chronology");
  const evidence = getSection(reportDocument, "evidence-overview");
  const documents = getSection(reportDocument, "supporting-documents");
  const financial = getSection(reportDocument, "financial-position");
  const people = getSection(reportDocument, "people-involved");
  const outstanding = getSection(reportDocument, "outstanding-matters");
  const actions = getSection(reportDocument, "next-actions");
  const headerProps = { title: "Investigation Report", subtitle: issue ? issue.displayLabel : summary.scopeLabel, caseName: reportDocument.source?.caseName, caseReference: reportDocument.source?.caseId, issueReference: issue?.reference, issueName: issue?.name, generatedAt: reportDocument.report?.generatedAt, preparedBy: presentation.preparedBy, approvedBy: presentation.approvedBy, version: presentation.version, documentStatus: presentation.documentStatus, confidentiality: presentation.confidentiality };
  return <ReportDocumentShell className={className} data-report-document="investigation" header={<ReportDocumentHeader {...headerProps} />} documentControl={<ReportDocumentControl purpose={presentation.purpose} audience={presentation.audience} scope={presentation.scope} reportingPeriod={presentation.reportingPeriod} exclusions={presentation.exclusions} completeness={presentation.completeness} generatedAt={reportDocument.report?.generatedAt} sourceRevision={reportDocument.source?.sourceRevision?.fingerprint} preparedBy={presentation.preparedBy} approvedBy={presentation.approvedBy} version={presentation.version} documentStatus={presentation.documentStatus} confidentiality={presentation.confidentiality} aiAssistance={presentation.aiAssistance} />} footer={<ReportDocumentFooter reportTitle="Investigation Report" caseName={reportDocument.source?.caseName} caseReference={reportDocument.source?.caseId} issueReference={issue?.reference} sourceRevision={reportDocument.source?.sourceRevision?.fingerprint} version={presentation.version} documentStatus={presentation.documentStatus} confidentiality={presentation.confidentiality} generatedAt={reportDocument.report?.generatedAt} />}>
    <ReportDocumentSection id="executive-summary" title="Executive Summary"><p>{summary.summaryText}</p><ReportDocumentCallout variant="limitation" title="Factual scope">This report presents structured records and relationships. It does not determine legal merit or whether an allegation is proven.</ReportDocumentCallout></ReportDocumentSection>
    <ReportDocumentSection id="current-position" title="Current Position" description={issue ? "User-authored current position and operational Issue metadata." : "Whole-case position available from the structured report model."}>{issue ? <><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-xs font-semibold text-neutral-500">Status</dt><dd>{humanStatus(current.status)}</dd></div><div><dt className="text-xs font-semibold text-neutral-500">Priority</dt><dd>{humanStatus(current.priority)}</dd></div><div><dt className="text-xs font-semibold text-neutral-500">Owner</dt><dd>{display(current.ownerName)}</dd></div><div><dt className="text-xs font-semibold text-neutral-500">Review date</dt><dd>{display(current.reviewDate)}</dd></div></dl>{current.purpose ? <p><strong>Purpose:</strong> {current.purpose}</p> : null}{current.currentPosition ? <ReportDocumentCallout variant="information" title="User-authored current position">{current.currentPosition}{current.updatedAt ? `\nLast updated: ${current.updatedAt}` : ""}</ReportDocumentCallout> : <p>No user-authored current position is recorded for this Issue.</p>}</> : <p>No reliable whole-case current focus is available in the presentation-safe report model.</p>}</ReportDocumentSection>
    <ReportDocumentSection id="snapshot" title="Investigation Snapshot"><ReportDocumentStatistics items={[{ key: "incident", label: "Incidents", value: statistics.incident || 0 }, { key: "evidence", label: "Evidence", value: statistics.evidence || 0 }, { key: "document", label: "Documents", value: statistics.document || 0 }, { key: "ledger", label: "Ledger", value: statistics.ledger || 0 }, { key: "strategy", label: "Strategy", value: statistics.strategy || 0 }, { key: "watch", label: "To Watch", value: statistics.watch || 0 }, { key: "linked", label: "Linked context", value: statistics.linkedContext || 0, note: "Not direct Issue membership" }, { key: "unresolved", label: "Unresolved references", value: statistics.unresolvedReferences || 0 }, { key: "findings", label: "Audit findings", value: statistics.auditFindings || 0 }]} /></ReportDocumentSection>
    <ReportDocumentSection id="key-findings" title="Key Findings" description="Deterministic structural observations; not factual or legal conclusions."><SimpleList items={findings} empty="No deterministic structural findings were generated. This does not confirm factual or legal completeness." /></ReportDocumentSection>
    <ReportDocumentSection id="narrative-chronology" title="Narrative Chronology" description="Concise chronology. The complete chronology appears in Appendix B."><ChronologyGroups groups={chronology.groups || []} /></ReportDocumentSection>
    <ReportDocumentSection id="evidence-overview" title="Evidence Overview"><ReportDocumentStatistics columns={3} items={[{ key: "total", label: "Evidence records", value: evidence.metadata?.total || 0 }, { key: "linked", label: "Linked to Incidents", value: evidence.metadata?.linked || 0 }, { key: "attachments", label: "With attachment metadata", value: evidence.metadata?.withAttachments || 0 }]} /><CompactRecords items={evidence.items || []} kind="Evidence records" /></ReportDocumentSection>
    <ReportDocumentSection id="supporting-documents" title="Supporting Documents"><ReportDocumentStatistics columns={3} items={[{ key: "total", label: "Documents", value: documents.metadata?.total || 0 }, { key: "linked", label: "Linked Documents", value: documents.metadata?.linked || 0 }, { key: "attachments", label: "With attachment metadata", value: documents.metadata?.withAttachments || 0 }]} /><CompactRecords items={documents.items || []} kind="Documents" /></ReportDocumentSection>
    {financial.id ? <ReportDocumentSection id="financial-position" title="Financial / Ledger Position" description="Currencies are reported separately and are never converted or combined."><ul className="space-y-2">{(financial.metadata?.totalsByCurrency || []).map((item) => <li key={item.currency}><strong>{item.currency}:</strong> total {item.total}; credit {item.credit}; debit {item.debit}; pending {item.pending}; disputed {item.disputed}; waived {item.waived}</li>)}</ul></ReportDocumentSection> : null}
    <ReportDocumentSection id="people-involved" title="People Involved"><ul className="grid gap-3 sm:grid-cols-2">{(people.items || []).map((party) => <li key={party.id} className="break-inside-avoid border-b border-neutral-200 pb-3 dark:border-neutral-700"><strong>{party.name}</strong><p className="text-sm text-neutral-600 dark:text-neutral-300">{[party.role, party.organisation].filter(Boolean).join(" · ") || "Role not recorded"}</p><p className="text-xs text-neutral-500">{party.directRecordAppearances} direct record appearance(s) · {party.recordTypes.map((type) => TYPE_LABELS[type] || type).join(", ")}</p></li>)}</ul>{!(people.items || []).length ? <p>No resolved Parties appear directly in this scope.</p> : null}</ReportDocumentSection>
    <ReportDocumentSection id="outstanding-matters" title="Outstanding Matters">{(outstanding.groups || []).map((group) => <section key={group.id} aria-labelledby={`${group.id}-heading`} className="mt-5 first:mt-0"><h3 id={`${group.id}-heading`} className="text-lg font-semibold">{group.label}</h3><div className="mt-2"><SimpleList items={group.items || []} empty="None recorded by the current deterministic checks." /></div></section>)}</ReportDocumentSection>
    <ReportDocumentSection id="next-actions" title="Next Actions" description="Existing structured actions only; no new advice is generated."><h3 className="text-lg font-semibold">Case actions</h3>{(actions.items || []).length ? <ul className="mt-3 space-y-3">{actions.items.map((action) => <li key={action.id} className="break-inside-avoid border-l-2 border-lime-600 pl-3"><strong>{action.action}</strong><p className="text-sm text-neutral-600 dark:text-neutral-300">Source: {action.sourceType} — {action.sourceTitle}{action.owner ? ` · Owner: ${action.owner}` : ""}{action.dueDate ? ` · Due: ${action.dueDate}` : ""}{action.status ? ` · Status: ${action.status}` : ""}</p></li>)}</ul> : <p className="mt-2">No structured next actions or reviews are recorded in this scope.</p>}<h3 className="mt-6 text-lg font-semibold">Data-quality remediation</h3><SimpleList items={actions.metadata?.dataQualityRemediation || []} empty="No deterministic data-quality remediation is currently listed." /></ReportDocumentSection>
    {(reportDocument.appendices || []).map((appendix) => <ReportDocumentAppendix key={appendix.id} id={appendix.id} label={appendix.label} title={appendix.title} description={appendix.type === "reference-index" ? "Technical identifiers are secondary references for traceability." : `Complete structured ${appendix.title.toLowerCase()} for the declared scope.`}>{appendix.type === "chronology" ? <ChronologyGroups groups={appendix.groups || []} /> : appendix.rows ? <AppendixTable appendix={appendix} /> : <SimpleList items={(appendix.items || []).map((item) => ({ ...item, text: item.message || `${TYPE_LABELS[item.recordType] || item.recordType}: ${item.title} (${item.recordId}; ${item.scopeRelation || item.code || "reference"})` }))} empty="No entries apply." />}</ReportDocumentAppendix>)}
  </ReportDocumentShell>;
}
