import {
  ReportDocumentAppendix, ReportDocumentCallout, ReportDocumentControl, ReportDocumentFooter,
  ReportDocumentHeader, ReportDocumentSection, ReportDocumentShell, ReportDocumentStatistics,
} from "./document/index.js";

function getSection(document, id) { return (document?.sections || []).find((item) => item.id === id) || {}; }
function display(value, fallback = "Not recorded") { return value === null || value === undefined || value === "" ? fallback : String(value); }
function human(value) { return display(value).replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function Empty({ children }) { return <p className="text-sm leading-6 text-neutral-600 dark:text-neutral-300 print:text-neutral-800">{children}</p>; }
function FindingList({ items = [], empty = "No deterministic items are recorded in this section." }) { return items.length ? <ul className="space-y-2">{items.map((item, index) => <li key={item.id || `${item.code || "item"}-${index}`} className="break-inside-avoid border-l-2 border-neutral-300 pl-3 dark:border-neutral-600 print:border-black"><p className="font-medium text-neutral-900 dark:text-neutral-100 print:text-black">{item.message || item.decision || item.action || item.title}</p>{item.source || item.code || item.dueDate ? <p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400 print:text-neutral-700">{[item.source || item.code, item.dueDate && `Due ${item.dueDate}`].filter(Boolean).join(" · ")}</p> : null}</li>)}</ul> : <Empty>{empty}</Empty>; }

function IssueRows({ items = [] }) {
  if (!items.length) return <Empty>No Issues are recorded for management review.</Empty>;
  return <div className="space-y-4">{items.map((issue) => <section key={issue.id} aria-labelledby={`management-${issue.id}-heading`} className="break-inside-avoid border-t border-neutral-300 pt-4 first:border-t-0 first:pt-0 dark:border-neutral-600 print:border-black"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><h3 id={`management-${issue.id}-heading`} className="break-words text-lg font-semibold text-neutral-950 dark:text-neutral-50 print:text-black">{issue.displayLabel}</h3><p className="mt-1 text-sm text-neutral-600 dark:text-neutral-300 print:text-neutral-800">{issue.purpose || "No Issue purpose is recorded."}</p></div><div className="flex flex-wrap gap-2 text-xs font-semibold"><span className="border border-neutral-400 px-2 py-1">Priority: {human(issue.priority)}</span><span className="border border-neutral-400 px-2 py-1">Status: {human(issue.status)}</span></div></div>{issue.currentPosition ? <div className="mt-3"><p className="text-xs font-semibold text-neutral-500 dark:text-neutral-400">User-authored current position</p><p className="mt-1 text-sm leading-6">{issue.currentPosition}</p></div> : null}<dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="font-semibold">Owner</dt><dd>{issue.owner}</dd></div><div><dt className="font-semibold">Review date</dt><dd>{display(issue.reviewDate)}</dd></div><div><dt className="font-semibold">Latest activity</dt><dd>{display(issue.latestActivity)}</dd></div><div><dt className="font-semibold">Outstanding findings</dt><dd>{issue.outstandingFindingCount}</dd></div></dl></section>)}</div>;
}

function AppendixContent({ appendix }) {
  if (appendix.type === "issue-summary") return <IssueRows items={appendix.items} />;
  if (appendix.type === "chronology") return <div className="space-y-5">{appendix.groups.map((group) => <section key={group.id}><h3 className="text-lg font-semibold">{group.label}</h3><ol className="mt-2 space-y-2">{(group.entries || []).map((entry) => <li key={`${entry.recordType}:${entry.recordId}`} className="border-l-2 border-neutral-300 pl-3 print:border-black"><span className="font-semibold">{entry.date || human(entry.dateStatus)}</span> — {entry.title} <span className="text-sm text-neutral-500">({human(entry.recordType)})</span></li>)}</ol></section>)}</div>;
  if (appendix.type === "strategy") return <FindingList items={appendix.items.map((item) => ({ ...item, message: item.title, source: [item.issueLabel, item.status, item.reviewDate && `Review ${item.reviewDate}`].filter(Boolean).join(" · ") }))} />;
  if (appendix.type === "reference-index") return <div className="min-w-0"><table className="w-full table-fixed border-collapse text-left text-sm"><caption className="mb-3 text-left text-sm text-neutral-600 dark:text-neutral-300">Technical record identifiers are secondary references.</caption><thead><tr><th scope="col" className="w-1/4 border-b border-neutral-400 p-2">Type</th><th scope="col" className="w-1/2 border-b border-neutral-400 p-2">Title</th><th scope="col" className="w-1/4 border-b border-neutral-400 p-2">Reference</th></tr></thead><tbody>{appendix.items.map((item) => <tr key={`${item.recordType}:${item.recordId}`}><td className="break-words border-b border-neutral-200 p-2">{human(item.recordType)}</td><td className="break-words border-b border-neutral-200 p-2">{item.title}</td><td className="break-all border-b border-neutral-200 p-2 font-mono text-xs">{item.recordId}</td></tr>)}</tbody></table></div>;
  return <FindingList items={appendix.items || []} />;
}

export default function ManagementReportArticle({ reportDocument }) {
  if (!reportDocument) return <div className="rounded-xl border border-dashed border-neutral-300 p-5 dark:border-neutral-700"><Empty>No Management Report document is available.</Empty></div>;
  const presentation = reportDocument.presentation || {};
  const executive = getSection(reportDocument, "executive-summary"); const current = getSection(reportDocument, "current-position"); const snapshot = getSection(reportDocument, "management-snapshot"); const issues = getSection(reportDocument, "major-issues"); const risks = getSection(reportDocument, "current-risks"); const progress = getSection(reportDocument, "progress"); const outstanding = getSection(reportDocument, "outstanding-matters"); const decisions = getSection(reportDocument, "management-decisions"); const actions = getSection(reportDocument, "next-actions");
  const header = <ReportDocumentHeader title="Management Report" subtitle="Executive case briefing" caseName={reportDocument.source?.caseName} generatedAt={reportDocument.report?.generatedAt} version={presentation.version} documentStatus={presentation.documentStatus} confidentiality={presentation.confidentiality} preparedBy={presentation.preparedBy} approvedBy={presentation.approvedBy} />;
  const control = <ReportDocumentControl purpose={presentation.purpose} audience={presentation.audience} scope={presentation.scope} reportingPeriod={presentation.reportingPeriod} exclusions={presentation.exclusions} completeness={presentation.completeness} generatedAt={reportDocument.report?.generatedAt} sourceRevision={reportDocument.source?.sourceRevision?.fingerprint} version={presentation.version} documentStatus={presentation.documentStatus} confidentiality={presentation.confidentiality} aiAssistance={presentation.aiAssistance} />;
  const footer = <ReportDocumentFooter reportTitle="Management Report" caseName={reportDocument.source?.caseName} sourceRevision={reportDocument.source?.sourceRevision?.fingerprint} version={presentation.version} documentStatus={presentation.documentStatus} confidentiality={presentation.confidentiality} generatedAt={reportDocument.report?.generatedAt} />;
  return <ReportDocumentShell aria-label="Management Report" header={header} documentControl={control} footer={footer}>
    <ReportDocumentSection id="executive-summary" title="Executive Summary"><p className="text-base leading-7">{executive.text}</p><ReportDocumentCallout variant="information" title="Management briefing scope">This report is a concise management summary. It does not replace the complete Investigation Report.</ReportDocumentCallout></ReportDocumentSection>
    <ReportDocumentSection id="current-position" title="Current Position" description="Current-position text below is user-authored Issue metadata, not an automated conclusion."><p><strong>Case status:</strong> {human(current.metadata?.caseStatus)}</p><IssueRows items={current.items || []} /></ReportDocumentSection>
    <ReportDocumentSection id="management-snapshot" title="Management Snapshot"><ReportDocumentStatistics columns={3} items={Object.entries(snapshot.metadata || {}).map(([key, value]) => ({ key, label: human(key.replace(/([A-Z])/g, " $1")), value }))} /></ReportDocumentSection>
    <ReportDocumentSection id="major-issues" title="Major Issues" description="Issues are ordered by recorded priority, review date, and human reference."><IssueRows items={issues.items || []} /></ReportDocumentSection>
    <ReportDocumentSection id="current-risks" title="Current Risks" description="Deterministic structural risks only; no legal or operational conclusions are inferred."><FindingList items={risks.items || []} empty="No critical or warning-level structural risks are currently detected. This does not establish factual or legal completeness." /></ReportDocumentSection>
    <ReportDocumentSection id="progress" title="Progress Since Previous Review"><ReportDocumentCallout variant="limitation" title="Historical comparison limitation">{progress.metadata?.limitation}</ReportDocumentCallout><p className="text-sm">{progress.metadata?.period}</p><FindingList items={(progress.items || []).map((item) => ({ ...item, message: `${human(item.type)}: ${item.title}`, source: item.loggedDate ? `Logged ${item.loggedDate}` : "Logged date unavailable" }))} empty="No records with logged dates in the recent activity window were identified." /></ReportDocumentSection>
    <ReportDocumentSection id="outstanding-matters" title="Outstanding Matters">{(outstanding.groups || []).map((group) => <section key={group.id} aria-labelledby={`outstanding-${group.id}`}><h3 id={`outstanding-${group.id}`} className="text-lg font-semibold">{group.label}</h3><div className="mt-2"><FindingList items={group.items || []} empty={`No ${group.label.toLowerCase()} matters are deterministically identified.`} /></div></section>)}</ReportDocumentSection>
    <ReportDocumentSection id="management-decisions" title="Management Decisions Required"><FindingList items={decisions.items || []} empty="No structured management decision requirement is currently recorded. This does not mean that no decision is needed." /></ReportDocumentSection>
    <ReportDocumentSection id="next-actions" title="Next Actions">{(actions.groups || []).map((group) => <section key={group.id} aria-labelledby={`actions-${group.id}`}><h3 id={`actions-${group.id}`} className="text-lg font-semibold">{group.label}</h3><div className="mt-2"><FindingList items={group.items || []} empty={`No ${group.label.toLowerCase()} actions are recorded.`} /></div></section>)}</ReportDocumentSection>
    {(reportDocument.appendices || []).map((appendix) => <ReportDocumentAppendix key={appendix.id} id={appendix.id} label={appendix.label} title={appendix.title}><AppendixContent appendix={appendix} /></ReportDocumentAppendix>)}
    {(reportDocument.notices || []).map((notice) => <ReportDocumentCallout key={notice.code} variant="limitation" title={notice.code}>{notice.message}</ReportDocumentCallout>)}
  </ReportDocumentShell>;
}
