import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { readFile } from "node:fs/promises";
import test from "node:test";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { transformWithOxc } from "vite";
import { buildManagementReportDocument } from "../../report/managementReportDocument.js";
import { buildCaseReportModel } from "../../report/reportModel.js";
import { getReportDefinition } from "../../report/reportDefinitions.js";

const runtimeUrl = import.meta.resolve("react/jsx-runtime"); const foundationUrl = new URL("./document/ReportDocumentFoundation.jsx", import.meta.url); const stylesUrl = new URL("./document/reportDocumentStyles.js", import.meta.url).href; const foundation = await transformWithOxc(await readFile(foundationUrl, "utf8"), foundationUrl.pathname); const foundationImportUrl = `data:text/javascript;base64,${Buffer.from(foundation.code.replaceAll('from "react/jsx-runtime"', `from "${runtimeUrl}"`).replaceAll('from "./reportDocumentStyles.js"', `from "${stylesUrl}"`)).toString("base64")}`; const articleUrl = new URL("./ManagementReportArticle.jsx", import.meta.url); const article = await transformWithOxc(await readFile(articleUrl, "utf8"), articleUrl.pathname); const { default: ManagementReportArticle } = await import(`data:text/javascript;base64,${Buffer.from(article.code.replaceAll('from "react/jsx-runtime"', `from "${runtimeUrl}"`).replaceAll('from "./document/index.js"', `from "${foundationImportUrl}"`)).toString("base64")}`);
function document() { const model = buildCaseReportModel({ id: "case", name: "Case", status: "open", issues: [{ id: "uuid-hidden", reference: "ISS-001", name: "Primary Issue", status: "open", priority: "critical", currentPosition: "A response is outstanding.", purpose: "Obtain a response.", createdAt: "2026-01-01", updatedAt: "2026-08-01" }], incidents: [{ id: "i1", title: "Incident", eventDate: "2026-07-01", sequenceGroupId: "uuid-hidden", sequenceGroup: "Primary Issue" }], evidence: [], documents: [], ledger: [], strategy: [], watchItems: [] }, { generatedAt: "2026-08-02T12:00:00Z", includeDiagnostics: true }); return buildManagementReportDocument(model, getReportDefinition("management"), { generatedAt: "2026-08-02T12:00:00Z" }); }
test("renders the complete executive Management structure with shared foundation", () => { const html = renderToStaticMarkup(React.createElement(ManagementReportArticle, { reportDocument: document() })); for (const label of ["Management Report", "Document control", "Executive Summary", "Current Position", "Management Snapshot", "Major Issues", "Current Risks", "Progress Since Previous Review", "Outstanding Matters", "Management Decisions Required", "Next Actions", "Appendix A"]) assert.match(html, new RegExp(label)); assert.match(html, /ISS-001 — Primary Issue/); assert.match(html, /User-authored/); });
test("uses semantic responsive dark and print presentation without internal or legacy labels", () => { const html = renderToStaticMarkup(React.createElement(ManagementReportArticle, { reportDocument: document() })); assert.match(html, /^<article/); assert.match(html, /<h1/); assert.match(html, /dark:/); assert.match(html, /print:/); assert.match(html, /sm:/); assert.doesNotMatch(html, />uuid-hidden<|Sequence Group|Sequence Chain|TODO|GPT prompt|Page \d+ of/i); });
