export const AI_TOOL_OPTIONS = [
  {
    id: "missing-function-summaries",
    title: "Missing Function Summaries",
    description: "Evidence records with missing or vague functionSummary fields.",
    purpose: "Find evidence records that need clearer proof-purpose summaries.",
    bestUsedFor: ["Investigation quality", "Evidence review"],
    contains: ["Case", "Evidence"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "ungrouped-incidents-audit",
    title: "Ungrouped Incidents Audit",
    description: "Incidents without a sequenceGroup, with linked context and existing group names.",
    purpose: "Review incidents that are not yet assigned to an issue chain.",
    bestUsedFor: ["Investigation quality", "Sequence review"],
    contains: ["Case", "Incidents", "Sequence Groups"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "ungrouped-evidence-audit",
    title: "Ungrouped Evidence Audit",
    description: "Evidence without a sequenceGroup, with resolved incident and record context.",
    purpose: "Review evidence that is not yet assigned to an issue chain.",
    bestUsedFor: ["Investigation quality", "Sequence review"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Sequence Groups"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "weak-links-audit",
    title: "Weak Links Audit",
    description: "Broken, missing, orphaned, and weak link diagnostics with record summaries.",
    purpose: "Find records that are poorly linked, unsupported, orphaned, or pointing to missing targets.",
    bestUsedFor: ["Investigation quality", "Developer/debug"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "chain-completion-pack",
    title: "Chain Completion Pack",
    description: "One selected sequence group with scoped records, linked context, and diagnostics.",
    purpose: "Review one sequence group for missing evidence, weak links, and completion gaps.",
    bestUsedFor: ["Sequence review", "Investigation quality"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger", "Sequence Groups"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "full-chain-gpt-pack",
    title: "Full Chain GPT Pack",
    description: "Complete bounded safe records for one sequence chain, including diagnostics and external linked records.",
    purpose: "Give a GPT the strongest bounded context for reviewing one complete issue chain.",
    bestUsedFor: ["Sequence review", "Legal specialist", "Management reporting"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger", "Timeline", "Sequence Groups"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "management-report-builder-pack",
    title: "Management Report Builder Pack",
    description: "Whole-case or sequence-group handoff package for a specialist Report Builder GPT.",
    purpose: "Prepare a whole-case or sequence-group handoff for management-facing report drafting.",
    bestUsedFor: ["Management reporting", "Legal specialist", "Whole case review"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger", "Reports", "Sequence Groups"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "case-slice-pack",
    title: "Case Slice Pack",
    description: "A custom selected set of record IDs with directly linked context.",
    purpose: "Send selected records and their direct linked context for focused GPT review.",
    bestUsedFor: ["Whole case review", "Investigation quality"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
];

export const AI_WORKSPACE_SECTIONS = [
  {
    id: "whole-case",
    title: "Whole Case",
    icon: "Briefcase",
    description: "Start with the whole investigation.",
    tasks: [
      {
        id: "review-entire-investigation",
        title: "Review My Entire Investigation",
        technicalTool: "AI Reasoning Snapshot JSON",
        actionKind: "reasoning-snapshot",
        purpose: "Give a GPT enough structured context to understand and review the whole case.",
        useThisWhen: "Use this first when you want broad case review, legal review, management review, or gap analysis.",
        bestGpt: ["Legal Specialist", "Management Specialist", "General ChatGPT", "Investigation Review GPT"],
        contains: ["Case", "Parties", "Incidents", "Evidence", "Documents", "Records", "Ledger", "Timeline", "Reports"],
        doesNotInclude: ["Original files", "Binary attachments", "Import capability"],
        safety: ["Read Only", "Not importable", "Does not change case data"],
      },
    ],
  },
  {
    id: "investigation-quality",
    title: "Investigation Quality",
    icon: "Search",
    description: "Find weak links, missing summaries, and records that still need organizing.",
    tasks: [
      {
        id: "find-investigation-gaps",
        title: "Find Investigation Gaps",
        toolId: "weak-links-audit",
        technicalTool: "Weak Links Audit",
        useThisWhen: "Use this when records feel disconnected, unsupported, duplicated, or hard to trust.",
        bestGpt: ["Investigation Review GPT", "Legal Specialist", "General ChatGPT"],
      },
      {
        id: "improve-evidence-summaries",
        title: "Improve Evidence Summaries",
        toolId: "missing-function-summaries",
        technicalTool: "Missing Function Summaries",
        useThisWhen: "Use this when evidence exists but its proof purpose is unclear or incomplete.",
        bestGpt: ["Investigation Review GPT", "Legal Specialist"],
      },
      {
        id: "review-ungrouped-incidents",
        title: "Review Ungrouped Incidents",
        toolId: "ungrouped-incidents-audit",
        technicalTool: "Ungrouped Incidents Audit",
        useThisWhen: "Use this when incidents need assigning to issue threads or sequence groups.",
        bestGpt: ["Investigation Review GPT", "General ChatGPT"],
      },
      {
        id: "review-ungrouped-evidence",
        title: "Review Ungrouped Evidence",
        toolId: "ungrouped-evidence-audit",
        technicalTool: "Ungrouped Evidence Audit",
        useThisWhen: "Use this when evidence needs assigning to issue threads or sequence groups.",
        bestGpt: ["Investigation Review GPT", "General ChatGPT"],
      },
    ],
  },
  {
    id: "report-writing",
    title: "Report Writing",
    icon: "Briefcase",
    description: "Prepare management-facing handoffs and specialist report-builder prompts.",
    tasks: [
      {
        id: "prepare-management-report",
        title: "Prepare Management Report",
        toolId: "management-report-builder-pack",
        technicalTool: "Management Report Builder Pack",
        useThisWhen: "Use this when a specialist GPT should draft or review a management-facing report.",
        bestGpt: ["Management Specialist", "Legal Specialist"],
      },
      {
        id: "specialist-review-prompt",
        title: "Specialist Review Prompt",
        toolId: "management-report-builder-pack",
        technicalTool: "Specialist Prompt",
        actionKind: "specialist-prompt",
        useThisWhen: "Use this when a report-builder GPT needs a formatted specialist instruction prompt.",
        bestGpt: ["Management Specialist", "Legal Specialist"],
      },
      {
        id: "improve-report-narrative",
        title: "Improve Report Narrative",
        technicalTool: "Narrative Polish",
        actionKind: "narrative-polish",
        purpose: "Copy the existing narrative polish prompt for the generated executive summary report.",
        useThisWhen: "Use this after generating a report when you want wording improved without changing facts.",
        bestGpt: ["Management Specialist", "General ChatGPT"],
        contains: ["Reports", "Sequence Groups"],
        doesNotInclude: ["Original files", "Binary attachments", "Import capability"],
        safety: ["Read Only", "Does not change case data"],
      },
    ],
  },
  {
    id: "issue-review",
    title: "Issue Review",
    icon: "Network",
    description: "Review one issue chain, sequence group, or selected record thread.",
    tasks: [
      {
        id: "review-investigation-thread",
        title: "Review Investigation Thread",
        toolId: "full-chain-gpt-pack",
        technicalTool: "Full Chain GPT Pack",
        useThisWhen: "Use this when one issue thread needs a complete evidence and chronology review.",
        bestGpt: ["Legal Specialist", "Investigation Review GPT", "Management Specialist"],
      },
      {
        id: "complete-investigation-thread",
        title: "Complete Investigation Thread",
        toolId: "chain-completion-pack",
        technicalTool: "Chain Completion Pack",
        useThisWhen: "Use this when one thread needs missing proof, weak link, or completion checks.",
        bestGpt: ["Investigation Review GPT", "Legal Specialist"],
      },
      {
        id: "review-selected-records",
        title: "Review Selected Records",
        toolId: "case-slice-pack",
        technicalTool: "Case Slice Pack",
        useThisWhen: "Use this when only a chosen set of records should be reviewed with their direct links.",
        bestGpt: ["General ChatGPT", "Investigation Review GPT"],
      },
    ],
  },
  {
    id: "advanced-ai-tools",
    title: "Advanced AI Tools",
    icon: "FileText",
    description: "Technical exports, imports, and debugging tools for expert workflows.",
    tasks: [
      {
        id: "advanced-reasoning-snapshot",
        title: "AI Reasoning Snapshot JSON",
        technicalTool: "AI Reasoning Snapshot JSON",
        actionKind: "reasoning-snapshot",
        purpose: "Copy the whole-case GPT reasoning snapshot directly.",
        useThisWhen: "Use this when you explicitly need the raw recommended GPT JSON.",
        bestGpt: ["Legal Specialist", "Management Specialist", "General ChatGPT", "Investigation Review GPT"],
        contains: ["Case", "Parties", "Incidents", "Evidence", "Documents", "Records", "Ledger", "Timeline", "Reports"],
        doesNotInclude: ["Original files", "Binary attachments", "Import capability"],
        safety: ["Read Only", "Not importable", "Does not change case data"],
      },
      {
        id: "advanced-link-map",
        title: "Link Map JSON",
        technicalTool: "Link Map JSON",
        actionKind: "link-map",
        purpose: "Copy the technical relationship map for debugging case links.",
        useThisWhen: "Use this when you need to inspect structure, missing links, or relationship graph issues.",
        bestGpt: ["Developer/debug", "Investigation Review GPT"],
        contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger"],
        doesNotInclude: ["Original files", "Binary attachments", "Import capability"],
        safety: ["Read Only", "Does not change case data"],
      },
      {
        id: "advanced-gpt-protocol-pack",
        title: "GPT Protocol Pack",
        technicalTool: "GPT Protocol Pack",
        actionKind: "protocol-pack",
        purpose: "Download custom GPT reference instructions and delta protocol examples.",
        useThisWhen: "Use this when configuring or debugging a specialist GPT, not when sending case data.",
        bestGpt: ["Developer/debug", "Specialist GPT"],
        contains: ["Diagnostics"],
        doesNotInclude: ["Case data", "Original files", "Binary attachments"],
        safety: ["Read Only", "Does not change case data"],
      },
      {
        id: "advanced-gpt-update",
        title: "GPT Update",
        technicalTool: "GPT Update",
        actionKind: "gpt-update",
        purpose: "Open the existing GPT Delta import workflow.",
        useThisWhen: "Use this only when importing a validated GPT delta back into the case.",
        bestGpt: ["Specialist GPT"],
        contains: ["Import/delta"],
        doesNotInclude: ["Backup export", "Binary attachments"],
        safety: ["Changes Case Data"],
      },
      {
        id: "advanced-sequence-group-audit",
        title: "Sequence Group Audit",
        technicalTool: "Sequence Group Audit",
        actionKind: "sequence-audit",
        purpose: "Open the existing sequence group audit export workflow.",
        useThisWhen: "Use this for focused issue or sequence review exports.",
        bestGpt: ["Investigation Review GPT", "Legal Specialist"],
        contains: ["Case", "Incidents", "Evidence", "Documents", "Sequence Groups"],
        doesNotInclude: ["Original files", "Binary attachments", "Import capability"],
        safety: ["Read Only", "Does not change case data"],
      },
    ],
  },
];
