export const AI_TOOL_OPTIONS = [
  {
    id: "missing-function-summaries",
    title: "Missing Function Summaries",
    description: "Evidence records with missing or vague functionSummary fields.",
    purpose: "Find evidence records that need clearer proof-purpose summaries.",
    bestUsedFor: ["Investigation quality", "Evidence review"],
    contains: ["Case", "Evidence"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "ungrouped-incidents-audit",
    title: "Ungrouped Incidents Audit",
    description: "Incidents without a sequenceGroup, with linked context and existing group names.",
    purpose: "Review incidents that are not yet assigned to an issue chain.",
    bestUsedFor: ["Investigation quality", "Sequence review"],
    contains: ["Case", "Incidents", "Sequence Groups"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "ungrouped-evidence-audit",
    title: "Ungrouped Evidence Audit",
    description: "Evidence without a sequenceGroup, with resolved incident and record context.",
    purpose: "Review evidence that is not yet assigned to an issue chain.",
    bestUsedFor: ["Investigation quality", "Sequence review"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Sequence Groups"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "weak-links-audit",
    title: "Weak Links Audit",
    description: "Broken, missing, orphaned, and weak link diagnostics with record summaries.",
    purpose: "Find records that are poorly linked, unsupported, orphaned, or pointing to missing targets.",
    bestUsedFor: ["Investigation quality", "Developer/debug"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "chain-completion-pack",
    title: "Chain Completion Pack",
    description: "One selected sequence group with scoped records, linked context, and diagnostics.",
    purpose: "Review one sequence group for missing evidence, weak links, and completion gaps.",
    bestUsedFor: ["Sequence review", "Investigation quality"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger", "Sequence Groups"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "full-chain-gpt-pack",
    title: "Full Chain GPT Pack",
    description: "Complete bounded safe records for one sequence chain, including diagnostics and external linked records.",
    purpose: "Give a GPT the strongest bounded context for reviewing one complete issue chain.",
    bestUsedFor: ["Sequence review", "Legal specialist", "Management reporting"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger", "Timeline", "Sequence Groups"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "management-report-builder-pack",
    title: "Management Report Builder Pack",
    description: "Whole-case or sequence-group handoff package for a specialist Report Builder GPT.",
    purpose: "Prepare a whole-case or sequence-group handoff for management-facing report drafting.",
    bestUsedFor: ["Management reporting", "Legal specialist", "Whole case review"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger", "Reports", "Sequence Groups"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
  {
    id: "case-slice-pack",
    title: "Case Slice Pack",
    description: "A custom selected set of record IDs with directly linked context.",
    purpose: "Send selected records and their direct linked context for focused GPT review.",
    bestUsedFor: ["Whole case review", "Investigation quality"],
    contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger"],
    doesNotInclude: ["Attachment files", "Binary evidence", "Import capability", "Parties"],
    actionType: "Clipboard",
    safety: "Read Only",
  },
];

export const AI_WORKSPACE_SECTIONS = [
  {
    id: "whole-case",
    title: "Whole Case",
    icon: "Briefcase",
    description: "Start with the whole investigation.",
    tasks: [
      {
        id: "review-entire-investigation",
        title: "Review My Entire Investigation",
        technicalTool: "AI Reasoning Snapshot JSON",
        actionKind: "reasoning-snapshot",
        purpose: "Give a GPT enough structured context to understand and review the whole case.",
        useThisWhen: "Use this first when you want broad case review, legal review, management review, or gap analysis.",
        bestGpt: ["Legal Specialist", "Management Specialist", "General ChatGPT", "Investigation Review GPT"],
        contains: ["Case", "Parties", "Incidents", "Evidence", "Documents", "Records", "Ledger", "Timeline", "Reports"],
        doesNotInclude: ["Original files", "Binary attachments", "Import capability"],
        safety: ["Read Only", "Not importable", "Does not change case data"],
      },
    ],
  },
  {
    id: "investigation-quality",
    title: "Investigation Quality",
    icon: "Search",
    description: "Find weak links, missing summaries, and records that still need organizing.",
    tasks: [
      {
        id: "find-investigation-gaps",
        title: "Find Investigation Gaps",
        toolId: "weak-links-audit",
        technicalTool: "Weak Links Audit",
        useThisWhen: "Use this when records feel disconnected, unsupported, duplicated, or hard to trust.",
        bestGpt: ["Investigation Review GPT", "Legal Specialist", "General ChatGPT"],
      },
      {
        id: "improve-evidence-summaries",
        title: "Improve Evidence Summaries",
        toolId: "missing-function-summaries",
        technicalTool: "Missing Function Summaries",
        useThisWhen: "Use this when evidence exists but its proof purpose is unclear or incomplete.",
        bestGpt: ["Investigation Review GPT", "Legal Specialist"],
      },
      {
        id: "review-ungrouped-incidents",
        title: "Review Ungrouped Incidents",
        toolId: "ungrouped-incidents-audit",
        technicalTool: "Ungrouped Incidents Audit",
        useThisWhen: "Use this when incidents need assigning to issue threads or sequence groups.",
        bestGpt: ["Investigation Review GPT", "General ChatGPT"],
      },
      {
        id: "review-ungrouped-evidence",
        title: "Review Ungrouped Evidence",
        toolId: "ungrouped-evidence-audit",
        technicalTool: "Ungrouped Evidence Audit",
        useThisWhen: "Use this when evidence needs assigning to issue threads or sequence groups.",
        bestGpt: ["Investigation Review GPT", "General ChatGPT"],
      },
    ],
  },
  {
    id: "report-writing",
    title: "Report Writing",
    icon: "Briefcase",
    description: "Prepare management-facing handoffs and specialist report-builder prompts.",
    tasks: [
      {
        id: "prepare-management-report",
        title: "Prepare Management Report",
        toolId: "management-report-builder-pack",
        technicalTool: "Management Report Builder Pack",
        useThisWhen: "Use this when a specialist GPT should draft or review a management-facing report.",
        bestGpt: ["Management Specialist", "Legal Specialist"],
      },
      {
        id: "specialist-review-prompt",
        title: "Specialist Review Prompt",
        toolId: "management-report-builder-pack",
        technicalTool: "Specialist Prompt",
        actionKind: "specialist-prompt",
        useThisWhen: "Use this when a report-builder GPT needs a formatted specialist instruction prompt.",
        bestGpt: ["Management Specialist", "Legal Specialist"],
      },
      {
        id: "improve-report-narrative",
        title: "Improve Report Narrative",
        technicalTool: "Narrative Polish",
        actionKind: "narrative-polish",
        purpose: "Copy the existing narrative polish prompt for the generated executive summary report.",
        useThisWhen: "Use this after generating a report when you want wording improved without changing facts.",
        bestGpt: ["Management Specialist", "General ChatGPT"],
        contains: ["Reports", "Sequence Groups"],
        doesNotInclude: ["Original files", "Binary attachments", "Import capability"],
        safety: ["Read Only", "Does not change case data"],
      },
    ],
  },
  {
    id: "issue-review",
    title: "Issue Review",
    icon: "Network",
    description: "Review one issue chain, sequence group, or selected record thread.",
    tasks: [
      {
        id: "review-investigation-thread",
        title: "Review Investigation Thread",
        toolId: "full-chain-gpt-pack",
        technicalTool: "Full Chain GPT Pack",
        useThisWhen: "Use this when one issue thread needs a complete evidence and chronology review.",
        bestGpt: ["Legal Specialist", "Investigation Review GPT", "Management Specialist"],
      },
      {
        id: "complete-investigation-thread",
        title: "Complete Investigation Thread",
        toolId: "chain-completion-pack",
        technicalTool: "Chain Completion Pack",
        useThisWhen: "Use this when one thread needs missing proof, weak link, or completion checks.",
        bestGpt: ["Investigation Review GPT", "Legal Specialist"],
      },
      {
        id: "review-selected-records",
        title: "Review Selected Records",
        toolId: "case-slice-pack",
        technicalTool: "Case Slice Pack",
        useThisWhen: "Use this when only a chosen set of records should be reviewed with their direct links.",
        bestGpt: ["General ChatGPT", "Investigation Review GPT"],
      },
    ],
  },
  {
    id: "advanced-ai-tools",
    title: "Advanced AI Tools",
    icon: "FileText",
    description: "Technical exports, imports, and debugging tools for expert workflows.",
    tasks: [
      {
        id: "advanced-reasoning-snapshot",
        title: "AI Reasoning Snapshot JSON",
        technicalTool: "AI Reasoning Snapshot JSON",
        actionKind: "reasoning-snapshot",
        purpose: "Copy the whole-case GPT reasoning snapshot directly.",
        useThisWhen: "Use this when you explicitly need the raw recommended GPT JSON.",
        bestGpt: ["Legal Specialist", "Management Specialist", "General ChatGPT", "Investigation Review GPT"],
        contains: ["Case", "Parties", "Incidents", "Evidence", "Documents", "Records", "Ledger", "Timeline", "Reports"],
        doesNotInclude: ["Original files", "Binary attachments", "Import capability"],
        safety: ["Read Only", "Not importable", "Does not change case data"],
      },
      {
        id: "advanced-link-map",
        title: "Link Map JSON",
        technicalTool: "Link Map JSON",
        actionKind: "link-map",
        purpose: "Copy the technical relationship map for debugging case links.",
        useThisWhen: "Use this when you need to inspect structure, missing links, or relationship graph issues.",
        bestGpt: ["Developer/debug", "Investigation Review GPT"],
        contains: ["Case", "Incidents", "Evidence", "Documents", "Ledger"],
        doesNotInclude: ["Original files", "Binary attachments", "Import capability"],
        safety: ["Read Only", "Does not change case data"],
      },
      {
        id: "advanced-gpt-protocol-pack",
        title: "GPT Protocol Pack",
        technicalTool: "GPT Protocol Pack",
        actionKind: "protocol-pack",
        purpose: "Download custom GPT reference instructions and delta protocol examples.",
        useThisWhen: "Use this when configuring or debugging a specialist GPT, not when sending case data.",
        bestGpt: ["Developer/debug", "Specialist GPT"],
        contains: ["Diagnostics"],
        doesNotInclude: ["Case data", "Original files", "Binary attachments"],
        safety: ["Read Only", "Does not change case data"],
      },
      {
        id: "advanced-gpt-update",
        title: "GPT Update",
        technicalTool: "GPT Update",
        actionKind: "gpt-update",
        purpose: "Open the existing GPT Delta import workflow.",
        useThisWhen: "Use this only when importing a validated GPT delta back into the case.",
        bestGpt: ["Specialist GPT"],
        contains: ["Import/delta"],
        doesNotInclude: ["Backup export", "Binary attachments"],
        safety: ["Changes Case Data"],
      },
      {
        id: "advanced-sequence-group-audit",
        title: "Sequence Group Audit",
        technicalTool: "Sequence Group Audit",
        actionKind: "sequence-audit",
        purpose: "Open the existing sequence group audit export workflow.",
        useThisWhen: "Use this for focused issue or sequence review exports.",
        bestGpt: ["Investigation Review GPT", "Legal Specialist"],
        contains: ["Case", "Incidents", "Evidence", "Documents", "Sequence Groups"],
        doesNotInclude: ["Original files", "Binary attachments", "Import capability"],
        safety: ["Read Only", "Does not change case data"],
      },
    ],
  },
];

export const AI_TASK_GUIDANCE = {
  "review-entire-investigation": {
    workflow: [
      "Copy the recommended GPT JSON.",
      "Open your preferred investigation, legal, or management GPT.",
      "Paste the export.",
      "Ask the GPT to review the whole case.",
      "Check the response against the source records in ProveIt.",
      "Optionally use GPT Update only for approved changes you want back in ProveIt.",
    ],
    recommendedGpt: "Workplace Investigation Specialist",
    alsoSuitableFor: ["General ChatGPT", "Legal Specialist", "Management Specialist"],
    exampleQuestions: [
      "Review this investigation for legal weaknesses.",
      "Identify unsupported allegations.",
      "Assess evidential strength.",
      "Recommend additional evidence.",
      "Identify procedural risks.",
      "Summarise the strongest and weakest parts of this case.",
    ],
  },
  "find-investigation-gaps": {
    workflow: [
      "Copy the gap audit export.",
      "Open an investigation review GPT.",
      "Paste the export.",
      "Ask it to identify missing proof, weak links, and unsupported records.",
      "Review each recommendation in ProveIt before changing the case.",
    ],
    recommendedGpt: "Investigation Review GPT",
    alsoSuitableFor: ["General ChatGPT", "Legal Specialist"],
    exampleQuestions: [
      "What evidence is missing?",
      "Which incidents are unsupported?",
      "Which documents need better links?",
      "Where are the weakest areas of the investigation?",
      "Which links should I fix first?",
    ],
  },
  "improve-evidence-summaries": {
    workflow: [
      "Copy the evidence summary export.",
      "Open an investigation review or legal GPT.",
      "Paste the export.",
      "Ask for clearer proof-purpose summaries.",
      "Use the response to update evidence summaries manually where appropriate.",
    ],
    recommendedGpt: "Investigation Review GPT",
    alsoSuitableFor: ["Legal Specialist", "General ChatGPT"],
    exampleQuestions: [
      "Which evidence summaries are too vague?",
      "Rewrite these evidence summaries in plain investigative language.",
      "What does each evidence item prove?",
      "Which evidence summaries need more context?",
      "Identify evidence that does not clearly support an allegation.",
    ],
  },
  "review-ungrouped-incidents": {
    workflow: [
      "Copy the ungrouped incidents audit.",
      "Open an investigation review GPT.",
      "Paste the export.",
      "Ask which incidents belong in existing issue threads.",
      "Review the recommendations before assigning sequence groups in ProveIt.",
    ],
    recommendedGpt: "Investigation Review GPT",
    alsoSuitableFor: ["General ChatGPT", "Legal Specialist"],
    exampleQuestions: [
      "Which incidents should be grouped together?",
      "Which incidents belong to an existing issue thread?",
      "Are any incidents duplicates or near-duplicates?",
      "Which incidents need more evidence before grouping?",
      "Suggest sequence groups for these incidents.",
    ],
  },
  "review-ungrouped-evidence": {
    workflow: [
      "Copy the ungrouped evidence audit.",
      "Open an investigation review GPT.",
      "Paste the export.",
      "Ask which evidence belongs to existing issue threads.",
      "Review the recommendations before assigning sequence groups in ProveIt.",
    ],
    recommendedGpt: "Investigation Review GPT",
    alsoSuitableFor: ["General ChatGPT", "Legal Specialist"],
    exampleQuestions: [
      "Which evidence items should be grouped with existing incidents?",
      "Which evidence items are not connected to an issue thread?",
      "Does any evidence appear unrelated?",
      "Which evidence needs better incident links?",
      "Suggest sequence groups for these evidence items.",
    ],
  },
  "prepare-management-report": {
    workflow: [
      "Choose whole case or a sequence group scope.",
      "Copy the management report pack.",
      "Open a management or report-writing GPT.",
      "Paste the pack.",
      "Ask for the report output you need.",
      "Review the draft against the ProveIt records before sharing.",
    ],
    recommendedGpt: "Management Specialist",
    alsoSuitableFor: ["Legal Specialist", "General ChatGPT"],
    exampleQuestions: [
      "Draft an executive summary.",
      "Prepare a management report.",
      "Highlight organisational risks.",
      "Summarise key findings.",
      "Produce recommended management actions.",
      "Identify what leadership needs to know first.",
    ],
  },
  "specialist-review-prompt": {
    workflow: [
      "Choose whole case or a sequence group scope.",
      "Copy the specialist prompt.",
      "Open the specialist report GPT.",
      "Paste the prompt.",
      "Review the generated report for accuracy before use.",
    ],
    recommendedGpt: "Management Specialist",
    alsoSuitableFor: ["Legal Specialist", "Specialist GPT"],
    exampleQuestions: [
      "Use this prompt to prepare a management-facing report.",
      "Create a specialist report from this handoff.",
      "Highlight key findings and risks.",
      "Separate facts, proof gaps, risks, and recommended actions.",
      "Keep the report grounded only in the supplied material.",
    ],
  },
  "improve-report-narrative": {
    workflow: [
      "Generate or review the current executive summary report.",
      "Copy the narrative polish prompt.",
      "Open a report-writing GPT.",
      "Paste the prompt.",
      "Paste approved polished text back into the report polish area if appropriate.",
    ],
    recommendedGpt: "Management Specialist",
    alsoSuitableFor: ["General ChatGPT", "Legal Specialist"],
    exampleQuestions: [
      "Improve the clarity of this report narrative.",
      "Make the executive summary more concise.",
      "Polish the wording without changing facts.",
      "Improve management-facing language.",
      "Make risks and actions easier to understand.",
    ],
  },
  "review-investigation-thread": {
    workflow: [
      "Select the sequence group to review.",
      "Copy the full chain GPT pack.",
      "Open an investigation or legal GPT.",
      "Paste the pack.",
      "Ask for a thread-level evidence and chronology review.",
      "Check recommended changes against ProveIt before acting.",
    ],
    recommendedGpt: "Legal Specialist",
    alsoSuitableFor: ["Investigation Review GPT", "Management Specialist", "General ChatGPT"],
    exampleQuestions: [
      "Analyse this investigation thread.",
      "Assess evidential strength.",
      "Identify contradictions.",
      "Recommend additional enquiries.",
      "Summarise the strongest and weakest proof in this thread.",
    ],
  },
  "complete-investigation-thread": {
    workflow: [
      "Select the sequence group to complete.",
      "Copy the chain completion pack.",
      "Open an investigation review GPT.",
      "Paste the pack.",
      "Ask what is missing before the thread is complete.",
      "Use the response as a checklist for further investigation.",
    ],
    recommendedGpt: "Investigation Review GPT",
    alsoSuitableFor: ["Legal Specialist", "General ChatGPT"],
    exampleQuestions: [
      "What is missing from this investigation thread?",
      "Which allegations need more support?",
      "Which evidence links are weak?",
      "What should I investigate next?",
      "What would make this thread report-ready?",
    ],
  },
  "review-selected-records": {
    workflow: [
      "Enter the selected record IDs.",
      "Copy the selected records pack.",
      "Open a suitable GPT.",
      "Paste the pack.",
      "Ask for analysis limited to those records and their direct context.",
      "Review any recommendations before updating ProveIt.",
    ],
    recommendedGpt: "General ChatGPT",
    alsoSuitableFor: ["Investigation Review GPT", "Legal Specialist"],
    exampleQuestions: [
      "Analyse only these selected records.",
      "Summarise their significance.",
      "Identify missing context.",
      "Suggest additional evidence.",
      "Explain how these records relate to each other.",
    ],
  },
  "advanced-reasoning-snapshot": {
    workflow: [
      "Copy the raw reasoning snapshot JSON.",
      "Open the GPT that requested this exact format.",
      "Paste the JSON.",
      "Ask for the specific review you need.",
      "Do not import any response unless you deliberately use GPT Update.",
    ],
    recommendedGpt: "Investigation Review GPT",
    alsoSuitableFor: ["General ChatGPT", "Legal Specialist", "Management Specialist"],
    exampleQuestions: [
      "Review this full case JSON.",
      "Find missing context in this investigation.",
      "Identify legal and evidential risks.",
      "Summarise the case structure.",
      "Recommend next investigative actions.",
    ],
  },
  "advanced-link-map": {
    workflow: [
      "Copy the link map JSON.",
      "Open a technical or investigation review GPT.",
      "Paste the relationship map.",
      "Ask it to inspect links, missing targets, and orphaned records.",
      "Use the response for manual cleanup in ProveIt.",
    ],
    recommendedGpt: "Developer/debug",
    alsoSuitableFor: ["Investigation Review GPT", "General ChatGPT"],
    exampleQuestions: [
      "Find broken or missing links in this map.",
      "Which records appear orphaned?",
      "Which relationships look suspicious?",
      "Explain the case relationship graph.",
      "What link cleanup should I do first?",
    ],
  },
  "advanced-gpt-protocol-pack": {
    workflow: [
      "Download the protocol pack in JSON or Markdown.",
      "Use it when configuring or debugging a custom GPT.",
      "Do not treat it as case evidence.",
      "Use the examples to understand accepted GPT Update formats.",
    ],
    recommendedGpt: "Specialist GPT",
    alsoSuitableFor: ["Developer/debug"],
    exampleQuestions: [
      "Explain how this ProveIt GPT protocol works.",
      "Check whether my GPT output follows this delta contract.",
      "Summarise the allowed update schema.",
      "Identify fields a GPT must not modify.",
      "Help configure a custom GPT using these rules.",
    ],
  },
  "advanced-gpt-update": {
    workflow: [
      "Only use this after reviewing GPT output carefully.",
      "Open GPT Update.",
      "Paste a valid ProveIt GPT delta.",
      "Validate the delta.",
      "Create a backup if prompted.",
      "Apply only if the preview matches your intent.",
    ],
    recommendedGpt: "Specialist GPT",
    alsoSuitableFor: ["Developer/debug"],
    exampleQuestions: [
      "Is this delta safe to import?",
      "Does this GPT update only change approved fields?",
      "What will this delta change?",
      "Are any record IDs invalid?",
      "Does this update create duplicate records?",
    ],
  },
  "advanced-sequence-group-audit": {
    workflow: [
      "Open the sequence group audit tool.",
      "Select the sequence group and output format.",
      "Copy or download the audit pack.",
      "Open an investigation or legal GPT.",
      "Ask for a focused issue-chain review.",
    ],
    recommendedGpt: "Investigation Review GPT",
    alsoSuitableFor: ["Legal Specialist", "General ChatGPT"],
    exampleQuestions: [
      "Audit this sequence group for weak proof.",
      "Which incidents in this thread need more evidence?",
      "Are any linked records outside the issue scope?",
      "What should be fixed before reporting?",
      "Summarise the issue-chain risks.",
    ],
  },
};
