import { useState } from "react";
import { formatLedgerAmount } from "../reports/reportArticleHelpers";
import { getLinkChipClasses } from "../linkChipStyles";
import LinkedChip from "../LinkedChip";
import PartyLinksRow from "./PartyLinksRow";
import { filterLedgerEntries, sortLedgerEntries } from "./ledgerViewHelpers";

const LEDGER_FILTERS = ["all", "rent", "installment", "deposit", "furniture", "repair", "utility", "legal", "other"];
const statusTone = { paid: "bg-lime-100 text-lime-700 border-lime-300", "part-paid": "bg-amber-100 text-amber-700 border-amber-300", unpaid: "bg-red-100 text-red-700 border-red-300", disputed: "bg-orange-100 text-orange-700 border-orange-300", refunded: "bg-blue-100 text-blue-700 border-blue-300" };
const proofTone = { confirmed: "bg-lime-100 text-lime-700 border-lime-300", partial: "bg-amber-100 text-amber-700 border-amber-300" };
const labelFor = (value) => String(value || "not recorded").replace(/-/g, " ");
const toneFor = (value, tones) => tones[value] || "bg-neutral-100 text-neutral-700 border-neutral-300";

function DetailValue({ label, children }) {
  if (children === "" || children == null) return null;
  return <div><dt className="text-[11px] font-bold uppercase tracking-wider text-neutral-400">{label}</dt><dd className="mt-0.5 text-sm text-neutral-700">{children}</dd></div>;
}

function LinkedRecords({ ids = [], getLinkedRecordMeta, onOpenLinkedRecord }) {
  if (!ids.length) return null;
  const resolved = ids.map((id) => ({ id, record: getLinkedRecordMeta(id) })).filter(({ record }) => record);
  const missing = ids.length - resolved.length;
  return <div className="border-t border-neutral-100 pt-3"><p className="text-[11px] font-bold uppercase tracking-wider text-neutral-400">Linked records</p><div className="mt-2 flex flex-wrap gap-1.5">{resolved.map(({ id, record }) => <LinkedChip key={id} onClick={() => onOpenLinkedRecord(id)} titleText={record.title || "Untitled record"} variant="record" className="flex items-center gap-1 text-left" leading={<span className="shrink-0 font-bold uppercase opacity-50">{record.typeLabel}</span>}>{record.title || "Untitled record"}</LinkedChip>)}{missing > 0 ? <span className={getLinkChipClasses("neutral", "cursor-default opacity-70")}>{missing} missing link{missing === 1 ? "" : "s"}</span> : null}</div></div>;
}

export default function LedgerTab({ ledgerEntries, ledgerFilter, onChangeFilter, onOpenLedgerModal, onDuplicateLedgerEntry, onDeleteLedgerEntry, getLinkedRecordMeta, onOpenLinkedRecord, parties = [] }) {
  const [selectedLedgerId, setSelectedLedgerId] = useState("");
  const entries = sortLedgerEntries(ledgerEntries || []);
  const filteredEntries = filterLedgerEntries(entries, ledgerFilter);
  const selectedEntry = entries.find((entry) => entry.id === selectedLedgerId) || null;
  const selectRow = (entryId) => setSelectedLedgerId(entryId);

  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold text-neutral-900">Ledger</h3><p className="mt-1 text-sm text-neutral-600">Review amounts, payment status, and supporting records.</p></div><button type="button" onClick={() => onOpenLedgerModal()} className="rounded-lg border border-lime-500 bg-white px-3 py-2 text-sm font-bold text-neutral-900 shadow-md transition-all hover:bg-lime-400/30 active:scale-95">Add Entry</button></div>
    <div className="flex flex-wrap gap-2 rounded-xl border border-neutral-200 bg-neutral-50 p-2" aria-label="Filter Ledger entries by category">{LEDGER_FILTERS.map((filter) => <button key={filter} type="button" onClick={() => onChangeFilter(filter)} aria-pressed={ledgerFilter === filter} className={`rounded-md border px-3 py-1 text-[11px] font-bold uppercase tracking-wider transition-all ${ledgerFilter === filter ? "border-lime-600 bg-lime-500 text-white shadow-sm" : "border-neutral-300 bg-white text-neutral-500 hover:bg-neutral-100"}`}>{filter}</button>)}</div>
    {(entries.length === 0 || filteredEntries.length === 0) ? <div className="rounded-2xl border border-dashed border-neutral-300 bg-neutral-50 p-5 text-sm text-neutral-600">{entries.length === 0 ? "No ledger entries yet." : "No ledger entries match this filter."}</div> : <div className="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-neutral-200 text-left"><thead className="bg-neutral-50 text-[11px] font-bold uppercase tracking-wider text-neutral-500"><tr><th className="px-4 py-3">Date / Period</th><th className="px-4 py-3">Entry</th><th className="px-4 py-3">Category</th><th className="px-4 py-3 text-right">Expected</th><th className="px-4 py-3 text-right">Paid</th><th className="px-4 py-3 text-right">Difference</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Proof</th></tr></thead><tbody className="divide-y divide-neutral-100">{filteredEntries.map((entry) => { const selected = selectedEntry?.id === entry.id; return <tr key={entry.id} tabIndex={0} role="button" aria-selected={selected} onClick={() => selectRow(entry.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); selectRow(entry.id); } }} className={`cursor-pointer transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-lime-500 ${selected ? "bg-lime-50" : "hover:bg-neutral-50"}`}><td className="whitespace-nowrap px-4 py-3 text-sm text-neutral-600">{entry.paymentDate || entry.dueDate || entry.period || "No date"}</td><td className="min-w-52 px-4 py-3"><p className="font-semibold text-neutral-900">{entry.label || "Untitled Ledger Entry"}</p>{entry.batchLabel ? <p className="mt-0.5 text-xs text-neutral-500">{entry.batchLabel}</p> : null}</td><td className="px-4 py-3 text-sm text-neutral-600">{entry.category || "other"}</td><td className="whitespace-nowrap px-4 py-3 text-right text-sm text-neutral-700">{formatLedgerAmount(entry.expectedAmount, entry.currency)}</td><td className="whitespace-nowrap px-4 py-3 text-right text-sm text-neutral-700">{formatLedgerAmount(entry.paidAmount, entry.currency)}</td><td className="whitespace-nowrap px-4 py-3 text-right text-sm font-semibold text-neutral-900">{formatLedgerAmount(entry.differenceAmount, entry.currency)}</td><td className="px-4 py-3"><span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase ${toneFor(entry.status, statusTone)}`}>{labelFor(entry.status)}</span></td><td className="px-4 py-3"><span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase ${toneFor(entry.proofStatus, proofTone)}`}>{labelFor(entry.proofStatus)}</span></td></tr>; })}</tbody></table></div></div>}
    {selectedEntry ? <section aria-labelledby="selected-ledger-entry" className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-neutral-500">Selected entry</p><h4 id="selected-ledger-entry" className="mt-1 text-lg font-semibold text-neutral-900">{selectedEntry.label || "Untitled Ledger Entry"}</h4></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => onOpenLedgerModal(selectedEntry, selectedEntry.id)} className="rounded-lg border border-lime-500 bg-white px-3 py-1.5 text-xs font-bold text-neutral-800 hover:bg-lime-50">Edit</button><button type="button" onClick={() => onDuplicateLedgerEntry(selectedEntry)} className="rounded-lg border border-neutral-300 bg-white px-3 py-1.5 text-xs font-bold text-neutral-700 hover:bg-neutral-100">Duplicate</button><button type="button" onClick={() => onDeleteLedgerEntry(selectedEntry.id)} className="rounded-lg border border-red-300 bg-white px-3 py-1.5 text-xs font-bold text-red-700 hover:bg-red-50">Delete</button></div></div><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><DetailValue label="Expected">{formatLedgerAmount(selectedEntry.expectedAmount, selectedEntry.currency)}</DetailValue><DetailValue label="Paid">{formatLedgerAmount(selectedEntry.paidAmount, selectedEntry.currency)}</DetailValue><DetailValue label="Difference">{formatLedgerAmount(selectedEntry.differenceAmount, selectedEntry.currency)}</DetailValue><DetailValue label="Status">{labelFor(selectedEntry.status)}</DetailValue><DetailValue label="Payment date">{selectedEntry.paymentDate}</DetailValue><DetailValue label="Due date">{selectedEntry.dueDate}</DetailValue><DetailValue label="Period">{selectedEntry.period}</DetailValue><DetailValue label="Category">{[selectedEntry.category, selectedEntry.subType].filter(Boolean).join(" / ")}</DetailValue><DetailValue label="Counterparty">{selectedEntry.counterparty}</DetailValue><DetailValue label="Method">{selectedEntry.method}</DetailValue><DetailValue label="Reference">{selectedEntry.reference}</DetailValue><DetailValue label="Proof">{[selectedEntry.proofType, selectedEntry.proofStatus].filter(Boolean).join(" / ")}</DetailValue></dl>{selectedEntry.notes ? <div className="mt-4 border-t border-neutral-100 pt-3"><p className="text-[11px] font-bold uppercase tracking-wider text-neutral-400">Notes</p><p className="mt-1 whitespace-pre-wrap text-sm text-neutral-700">{selectedEntry.notes}</p></div> : null}<div className="mt-4"><PartyLinksRow linkedPartyIds={selectedEntry.linkedPartyIds} parties={parties} /></div><LinkedRecords ids={selectedEntry.linkedRecordIds || []} getLinkedRecordMeta={getLinkedRecordMeta} onOpenLinkedRecord={onOpenLinkedRecord} /></section> : null}
  </div>;
}
