export default function StrategyDeltaModal({ text, error, validation, selectedIndexes, staleConfirmed, onChangeText, onValidate, onToggleProposal, onStaleConfirm, onApply, onClose }) {
  const proposals = validation?.planned || [];
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="flex max-h-[90vh] w-full max-w-3xl flex-col rounded-2xl bg-white shadow-xl">
        <div className="border-b border-neutral-200 p-5"><h2 className="text-xl font-semibold text-neutral-900">Update from AI</h2><p className="mt-1 text-sm text-neutral-600">Paste a Strategy Delta, review each proposal, and apply only the selected low-risk Strategy changes.</p></div>
        <div className="flex-1 space-y-4 overflow-y-auto p-5">
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">ProveIt remains authoritative. This workflow cannot delete records, alter Goals, change Strategy status or decision status, or modify non-Strategy case data.</div>
          <textarea value={text} onChange={(event) => onChangeText(event.target.value)} placeholder='{"contract":"proveit-strategy-delta","version":"1.0",...}' className="min-h-48 w-full rounded-lg border border-neutral-300 p-3 font-mono text-sm text-neutral-800 outline-none focus:border-lime-500" />
          {error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-700">{error}</div>}
          {validation?.stale && <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950"><strong>Stale AI context.</strong> This case is now revision {validation.currentRevision}, while the AI used revision {validation.baseRevision}. Review the proposals carefully; ProveIt will not merge conflicts automatically.<label className="mt-3 flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={staleConfirmed} onChange={(event) => onStaleConfirm(event.target.checked)} />I understand this stale-context warning and still want to apply selected proposals.</label></div>}
          {validation && <section className="space-y-3 rounded-lg border border-neutral-200 bg-neutral-50 p-4"><h3 className="font-semibold text-neutral-900">Proposal review</h3>{proposals.map((proposal) => <label key={proposal.index} className="block rounded-lg border border-neutral-200 bg-white p-3"><div className="flex items-start gap-3"><input type="checkbox" checked={selectedIndexes.includes(proposal.index)} onChange={(event) => onToggleProposal(proposal.index, event.target.checked)} className="mt-1 h-4 w-4" /><div className="min-w-0 flex-1"><div className="font-semibold text-neutral-900">{proposal.preview.title}</div><div className="mt-2 grid gap-2 text-xs sm:grid-cols-2"><div><span className="font-bold uppercase text-neutral-400">Current</span><p className="mt-1 whitespace-pre-wrap text-neutral-600">{proposal.preview.before || "—"}</p></div><div><span className="font-bold uppercase text-neutral-400">Proposed</span><p className="mt-1 whitespace-pre-wrap text-neutral-900">{proposal.preview.after || "—"}</p></div></div>{proposal.preview.reason && <p className="mt-2 text-xs text-neutral-600"><strong>Reason:</strong> {proposal.preview.reason}</p>}{proposal.preview.detail && <p className="mt-2 text-xs text-neutral-600">New Strategy fields: {Object.keys(proposal.preview.detail).join(", ")}</p>}</div></div></label>)}</section>}
        </div>
        <div className="flex flex-wrap justify-end gap-2 border-t border-neutral-200 p-5"><button type="button" onClick={onClose} className="rounded-md border border-neutral-300 bg-white px-4 py-2 text-sm font-semibold text-neutral-700">Cancel</button><button type="button" onClick={onValidate} className="rounded-md border border-lime-500 bg-white px-4 py-2 text-sm font-semibold text-neutral-900">Validate</button><button type="button" disabled={!validation || selectedIndexes.length === 0 || (validation.stale && !staleConfirmed)} onClick={onApply} className="rounded-md border border-lime-600 bg-lime-500 px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:border-neutral-300 disabled:bg-neutral-200 disabled:text-neutral-500">Apply selected ({selectedIndexes.length})</button></div>
      </div>
    </div>
  );
}
