import assert from "node:assert/strict";
import test from "node:test";
import { buildCaseAuditDocument } from "./caseAuditDocument.js";
import { buildCaseReportModel } from "./reportModel.js";
import { getReportDefinition } from "./reportDefinitions.js";
import { getReportDocumentSection, validateReportDocument } from "./reportDocument.js";

const generatedAt = "2026-07-26T12:00:00Z";
function build(caseData, options = {}) { const model = buildCaseReportModel(caseData, { includeArchived: true, includeDiagnostics: true, generatedAt, ...options }); return buildCaseAuditDocument(model, getReportDefinition("caseAudit"), { generatedAt }); }
function brokenCase() { return { id: "case-broken", parties: [{ id: "p1", name: "Same" }, { id: "p2", name: "same", role: "Witness" }, { id: "p3" }], incidents: [{ id: "i1", title: "i1", eventDate: "bad", linkedRecordIds: ["i1", "missing"], linkedEvidenceIds: ["i1"], linkedPartyIds: ["missing-party"], archived: true, sequenceGroup: "Unknown Group", outcome: "" }], evidence: [{ id: "e1", title: "Evidence", eventDate: "", attachments: [{ id: "", name: "", type: "" }] }], documents: [{ id: "d1", title: "Document", documentDate: "2026-01-01", attachments: [{ id: "a", name: "same.pdf", type: "application/pdf" }, { id: "a", name: "same.pdf", type: "application/pdf" }] }], ledger: [{ id: "l1", title: "Bad amount", date: "2026-01-02", amount: "not-money", currency: "EUR" }, { id: "l2", title: "USD", date: "2026-01-03", amount: 10, currency: "USD", status: "pending" }, { id: "l3", title: "Status note", date: "2026-01-04", isStatusNote: true, amount: 5, currency: "EUR", status: "active" }], strategy: [{ id: "s1", title: "Strategy", reviewDate: "2020-01-01", status: "active", nextSteps: [] }], watchItems: [{ id: "w1", title: "Watch", reviewDate: "2020-01-01", status: "active" }] }; }

test("builds every stable audit category with all severity levels and no duplicate IDs", () => { const document = build(brokenCase()); const categories = getReportDocumentSection(document, "findings-by-category").categories; assert.deepEqual(categories.map((item) => item.id), ["record-completeness", "date-quality", "link-integrity", "party-integrity", "attachment-proof-metadata", "sequence-group-coverage", "ledger-integrity", "strategy-completeness", "archive-visibility", "case-metadata"]); const findings = categories.flatMap((item) => item.findings); assert.equal(new Set(findings.map((item) => item.id)).size, findings.length); assert.deepEqual(new Set(findings.map((item) => item.severity)), new Set(["critical", "warning", "information"])); assert.ok(findings.every((item) => item.code && item.category && item.id && item.message)); assert.equal(validateReportDocument(document).valid, true); });

test("audits malformed dates unresolved self and duplicate links and unresolved parties", () => { const findings = getReportDocumentSection(build(brokenCase()), "findings-by-severity").items; for (const code of ["RECORD_MALFORMED_PRIMARY_DATE", "RECORD_SELF_LINK", "RECORD_DUPLICATE_LINK", "UNRESOLVED_RECORD_REFERENCE", "UNRESOLVED_PARTY_REFERENCE"]) assert.ok(findings.some((item) => item.code === code), code); assert.equal(findings.filter((item) => item.code === "UNRESOLVED_RECORD_REFERENCE").length, 1); });

test("audits attachment metadata Ledger currency and strategy and Watch completeness", () => { const source = brokenCase(); source.evidence[0].attachments = [{ name: "evidence-file" }, { id: "attachment-without-name" }]; source.ledger[0].currency = "EURO"; const document = build(source); const findings = getReportDocumentSection(document, "findings-by-severity").items; for (const code of ["ATTACHMENT_MISSING_ID", "ATTACHMENT_MISSING_FILENAME", "ATTACHMENT_MISSING_MIME_TYPE", "ATTACHMENT_DUPLICATE_METADATA", "LEDGER_MALFORMED_AMOUNT", "LEDGER_STATUS_NOTE_HAS_AMOUNT", "LEDGER_MISSING_PROOF_STATE", "LEDGER_MIXED_CURRENCIES", "LEDGER_UNRECOGNISED_CURRENCY_LABEL", "LEDGER_PENDING_ENTRY", "STRATEGY_MISSING_OBJECTIVE", "STRATEGY_ACTIVE_NO_NEXT_STEPS", "STRATEGY_REVIEW_PAST_DUE", "WATCH_REVIEW_PAST_DUE", "WATCH_NO_CONTEXT_LINK"]) assert.ok(findings.some((item) => item.code === code), code); const ledger = getReportDocumentSection(document, "ledger-integrity").metadata; assert.equal(ledger.currenciesAreCombined, false); assert.deepEqual(ledger.totalsByCurrency.map((item) => item.currency), ["EUR", "USD"]); assert.equal(ledger.totalsByCurrency.find((item) => item.currency === "USD").pending, 10); });

test("Sequence Group scope audits direct membership cross-group links and metadata-only groups", () => { const caseData = { id: "case", name: "Case", status: "active", category: "test", incidents: [{ id: "i1", title: "Incident", eventDate: "2026-01-01", status: "active", description: "Detail", sequenceGroup: "Alpha", linkedEvidenceIds: ["e1"] }], evidence: [{ id: "e1", title: "Evidence", eventDate: "2026-01-02", status: "active", evidenceType: "email", source: "Inbox", sequenceGroup: "Beta", linkedIncidentIds: ["i1"] }] }; const scoped = build(caseData, { scope: "sequenceGroup", sequenceGroupName: "alpha", sequenceGroupMeta: { Alpha: { description: "A" }, Beta: { description: "B" }, Empty: { description: "Metadata only" } } }); assert.equal(scoped.summary.scopedRecordCount, 1); assert.ok(getReportDocumentSection(scoped, "findings-by-severity").items.some((item) => item.code === "SEQUENCE_GROUP_CROSS_GROUP_LINK")); const empty = build(caseData, { scope: "sequenceGroup", sequenceGroupName: "Empty", sequenceGroupMeta: { Empty: { description: "Metadata only" } } }); assert.equal(empty.source.scope.isValid, true); assert.equal(empty.summary.scopedRecordCount, 0); assert.equal(getReportDocumentSection(empty, "sequence-group-coverage").metadata.selectedGroup.metadataOnly, true); const missing = build(caseData, { scope: "sequenceGroup", sequenceGroupName: "Missing" }); assert.equal(missing.source.scope.isValid, false); assert.equal(missing.summary.scopedRecordCount, 0); });

test("a representative complete case produces the explicit no-findings status", () => { const source = { id: "clean", name: "Clean", status: "active", category: "investigation", parties: [{ id: "p", name: "Alex", role: "Witness" }], incidents: [{ id: "i", title: "Incident", eventDate: "2026-01-01", status: "active", description: "Detail", sequenceGroup: "Alpha", linkedEvidenceIds: ["e"], linkedPartyIds: ["p"] }], evidence: [{ id: "e", title: "Evidence", eventDate: "2026-01-02", status: "active", evidenceType: "email", source: "Inbox", sequenceGroup: "Alpha", linkedIncidentIds: ["i"] }] }; const document = build(source, { sequenceGroupMeta: { Alpha: { description: "Group" } } }); assert.equal(document.summary.totalFindings, 0); assert.equal(document.summary.auditStatus, "No critical structural issues detected"); });

test("is deterministic serialisable binary-safe and immutable", () => { const source = brokenCase(); source.documents[0].attachments[0].dataUrl = "data:application/pdf;base64,AAA"; const snapshot = structuredClone(source); const model = buildCaseReportModel(source, { generatedAt }); const first = buildCaseAuditDocument(model, getReportDefinition("caseAudit"), { generatedAt }); const second = buildCaseAuditDocument(model, getReportDefinition("caseAudit"), { generatedAt }); assert.deepEqual(first, second); assert.deepEqual(source, snapshot); assert.doesNotMatch(JSON.stringify(first), /base64|data:application/); assert.doesNotThrow(() => JSON.stringify(first)); });

test("empty and malformed models remain safe", () => { const document = buildCaseAuditDocument({}, getReportDefinition("caseAudit"), { generatedAt }); assert.equal(document.summary.scopedRecordCount, 0); assert.equal(document.summary.auditStatus, "Critical structural issues detected"); assert.equal(validateReportDocument(document).valid, true); });
