import assert from "node:assert/strict";
import test from "node:test";
import { buildCaseReportModel } from "./reportModel.js";
import { getReportDefinition } from "./reportDefinitions.js";
import { getReportDocumentSection, validateReportDocument } from "./reportDocument.js";
import { buildChronologyReportDocument } from "./chronologyReportDocument.js";

const source = { id: "case-2", name: "Chronology Case", incidents: [{ id: "i1", title: "Incident", eventDate: "2025-12-31", sequenceGroup: "Alpha", linkedEvidenceIds: ["e2"] }], evidence: [{ id: "e1", title: "Evidence", eventDate: "2026-01-02" }, { id: "e2", title: "Same day A", eventDate: "2026-01-03", sequenceGroup: "Elsewhere" }], documents: [{ id: "d1", title: "Document", documentDate: "2026-01-03", sequenceGroup: "Alpha" }], ledger: [{ id: "l1", title: "Ledger", date: "bad" }], strategy: [{ id: "s1", title: "Strategy" }], watchItems: [{ id: "w1", title: "Watch", reviewDate: "2026-02-01", archived: true }] };
function documentFor(options = {}) { const model = buildCaseReportModel(source, { includeArchived: true, ...options, generatedAt: "2026-07-26T12:00:00Z" }); return buildChronologyReportDocument(model, getReportDefinition("chronologyReport"), { generatedAt: "2026-07-26T12:00:00Z" }); }

test("uses the canonical chronology across all six record types including Watch", () => { const document = documentFor(); const entries = getReportDocumentSection(document, "chronology").groups.flatMap((group) => group.entries); assert.deepEqual(new Set(entries.map((item) => item.recordType)), new Set(["incident", "evidence", "document", "ledger", "strategy", "watch"])); assert.equal(document.summary.countByRecordType.watch, 1); assert.equal(document.summary.totalChronologyEntries, 7); assert.equal(validateReportDocument(document).valid, true); });

test("preserves valid ordering and groups malformed then missing dates last", () => { const document = documentFor(); const groups = getReportDocumentSection(document, "chronology").groups; assert.deepEqual(groups.map((group) => group.id), ["month-2025-12", "month-2026-01", "month-2026-02", "malformed-dates", "missing-dates"]); const january = groups[1].entries; assert.deepEqual(january.map((entry) => entry.recordId), ["e1", "d1", "e2"]); assert.equal(document.summary.earliestValidDate, "2025-12-31"); assert.equal(document.summary.latestValidDate, "2026-02-01"); });

test("Sequence Group scope uses direct assignment and does not expand linked context", () => { const document = documentFor({ scope: "sequenceGroup", sequenceGroupName: "ALPHA" }); const entries = getReportDocumentSection(document, "chronology").groups.flatMap((group) => group.entries); assert.deepEqual(entries.map((item) => item.recordId), ["i1", "d1"]); assert.doesNotMatch(JSON.stringify(entries), /e2/); assert.match(document.notices.find((item) => item.code === "DIRECT_ASSIGNMENT_SCOPE").message, /not automatically added/); });

test("handles missing groups all-undated records and archive exclusion", () => { const missing = documentFor({ scope: "sequenceGroup", sequenceGroupName: "Missing" }); assert.equal(missing.source.scope.isValid, false); assert.equal(missing.summary.totalChronologyEntries, 0); const undatedModel = buildCaseReportModel({ strategy: [{ id: "s", title: "Undated" }] }); const undated = buildChronologyReportDocument(undatedModel, getReportDefinition("chronologyReport")); assert.equal(getReportDocumentSection(undated, "chronology").groups[0].groupType, "missing"); const excludedModel = buildCaseReportModel(source, { includeArchived: false }); const excluded = buildChronologyReportDocument(excludedModel, { ...getReportDefinition("chronologyReport"), includeArchived: false }); assert.equal(excluded.summary.countByRecordType.watch, 0); });

test("does not mutate source data and serialises deterministically", () => { const input = structuredClone(source); const snapshot = structuredClone(input); const model = buildCaseReportModel(input, { generatedAt: "2026-07-26T12:00:00Z" }); const first = buildChronologyReportDocument(model, getReportDefinition("chronologyReport"), { generatedAt: "2026-07-26T12:00:00Z" }); const second = buildChronologyReportDocument(model, getReportDefinition("chronologyReport"), { generatedAt: "2026-07-26T12:00:00Z" }); assert.deepEqual(first, second); assert.deepEqual(input, snapshot); assert.doesNotThrow(() => JSON.stringify(first)); });
