import { buildCaseAuditDocument } from "./caseAuditDocument.js";
import { buildChronologyReportDocument } from "./chronologyReportDocument.js";
import { createReportDocument, getReportDocumentSection } from "./reportDocument.js";
import { getReportDefinition } from "./reportDefinitions.js";
import { CLIENT_REPORT_PROMPT_REVISION, getClientNarrativeRevisionState } from "./clientReportValidation.js";

function section(document, id) { return getReportDocumentSection(document, id) || {}; }
function normalize(value) { return String(value || "").trim().toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu, " ").trim(); }
function issueForRecord(record, issues) { return issues.find((issue) => issue.name === record.sequenceGroup); }
function readableRef(record, issues) { return { type: record.type, title: record.title, recordId: record.id, issueLabel: issueForRecord(record, issues)?.displayLabel || record.sequenceGroup || "" }; }
function actions(records, issues, parties) { const items = []; issues.filter((issue) => issue.reviewDate).forEach((issue) => items.push({ id: `${issue.id}:review`, action: `Review ${issue.displayLabel}`, source: "Issue review", sourceType: "structured", issueLabel: issue.displayLabel, owner: issue.ownerPartyId ? parties.find((party) => party.id === issue.ownerPartyId)?.name || "Unresolved owner" : "", dueDate: issue.reviewDate, status: issue.status || "" })); records.filter((record) => record.type === "strategy" && !record.archived).forEach((record) => (record.details?.nextSteps || []).forEach((action, index) => items.push({ id: `${record.id}:step:${index}`, action, source: "Strategy", sourceType: "structured", issueLabel: issueForRecord(record, issues)?.displayLabel || record.sequenceGroup, owner: record.details?.ownerPartyId ? parties.find((party) => party.id === record.details.ownerPartyId)?.name || "Unresolved owner" : "", dueDate: record.details?.reviewDate || "", status: record.status || "", recordReference: readableRef(record, issues) }))); records.filter((record) => record.type === "watch" && !record.archived && record.details?.reviewDate).forEach((record) => items.push({ id: `${record.id}:review`, action: `Review monitored matter: ${record.title}`, source: "To Watch review", sourceType: "structured", issueLabel: issueForRecord(record, issues)?.displayLabel || record.sequenceGroup, owner: "", dueDate: record.details.reviewDate, status: record.status || "", recordReference: readableRef(record, issues) })); return items.sort((a, b) => (a.dueDate || "9999").localeCompare(b.dueDate || "9999") || a.action.localeCompare(b.action)); }

export function buildClientReportDocument(reportModel, definition = getReportDefinition("client"), options = {}) {
  const model = reportModel && typeof reportModel === "object" ? reportModel : {}; const generatedAt = options.generatedAt || model.generatedAt || new Date(0).toISOString(); const narrative = options.generatedNarrative || {}; const narrativeMeta = options.generatedNarrativeMeta || {}; const records = model.records?.primaryScopedRecords || []; const issues = model.sequenceGroups || []; const parties = model.parties || [];
  const audit = buildCaseAuditDocument(model, getReportDefinition("caseAudit"), { generatedAt }); const chronology = buildChronologyReportDocument(model, getReportDefinition("chronologyReport"), { generatedAt }); const findings = section(audit, "findings-by-severity").items || []; const chronologyGroups = section(chronology, "chronology").groups || [];
  const revisionState = getClientNarrativeRevisionState(narrativeMeta.sourceRevision, model.sourceRevision?.fingerprint); const hasNarrative = Boolean(narrative.reportTitle || narrative.yourSituation || narrative.currentPosition || narrative.issues?.length);
  const issueRows = issues.map((issue) => { const matchingNarrative = (narrative.issues || []).find((item) => normalize(item.title).includes(normalize(issue.name)) || normalize(issue.name).includes(normalize(item.title))); const directRecords = records.filter((record) => record.sequenceGroup === issue.name); return { id: issue.id, reference: issue.issueReference || "", displayLabel: issue.displayLabel, name: issue.name, purpose: issue.purpose, status: issue.status || "open", priority: issue.priority || "normal", owner: issue.ownerPartyId ? parties.find((party) => party.id === issue.ownerPartyId)?.name || "Unresolved owner" : "", reviewDate: issue.reviewDate, currentPosition: issue.currentPosition, source: "user_authored", statistics: { incidents: directRecords.filter((record) => record.type === "incident").length, evidence: directRecords.filter((record) => record.type === "evidence").length, documents: directRecords.filter((record) => record.type === "document").length }, narrative: matchingNarrative ? { source: "ai_assisted", whatHappened: matchingNarrative.whatHappened, explanation: matchingNarrative.whatThisMeans || [], supportingReferences: matchingNarrative.keyProof || [] } : null, recordReferences: directRecords.slice(0, 8).map((record) => readableRef(record, issues)) }; });
  const incidentRecords = records.filter((record) => record.type === "incident"); const evidenceRecords = records.filter((record) => record.type === "evidence"); const documentRecords = records.filter((record) => record.type === "document"); const resolvedEvidenceLinks = incidentRecords.filter((record) => (record.links || []).some((link) => link.status === "resolved" && link.targetType === "evidence")).length;
  const outstanding = findings.filter((finding) => finding.severity !== "information").map((finding) => ({ id: finding.id, message: finding.message, recordType: finding.recordType, title: finding.title, recordReference: records.find((record) => record.id === finding.recordId) ? readableRef(records.find((record) => record.id === finding.recordId), issues) : null, source: "structured" })); const nextActions = actions(records, issues, parties);
  const appendices = [ ...(issueRows.length ? [{ id: "appendix-issues", label: "Appendix A", title: "Issue Reference List", type: "issues", items: issueRows.map((issue) => ({ displayLabel: issue.displayLabel, name: issue.name, purpose: issue.purpose, status: issue.status, priority: issue.priority, owner: issue.owner, reviewDate: issue.reviewDate, currentPosition: issue.currentPosition, statistics: issue.statistics, recordReferences: issue.recordReferences })) }] : []), ...(chronologyGroups.length ? [{ id: "appendix-chronology", label: "Appendix B", title: "Key Chronology", type: "chronology", groups: chronologyGroups }] : []), { id: "appendix-records", label: "Appendix C", title: "Supporting Record Index", type: "records", items: records.map((record) => readableRef(record, issues)) }, ...(outstanding.length ? [{ id: "appendix-outstanding", label: "Appendix D", title: "Outstanding Matters Index", type: "outstanding", items: outstanding }] : []) ];
  const report = createReportDocument({ definition, model, generatedAt, title: "Client Report", notices: [{ code: "AI_ASSISTED_DRAFT", severity: "warning", message: "Some explanatory sections may be AI-assisted. They are not automatically verified and require human review before sharing." }], summary: { hasNarrative, revisionState, caseStatus: model.sourceCase?.status || "", activeIssueCount: issues.filter((issue) => !["resolved", "archived"].includes(issue.status)).length, outstandingFindingCount: outstanding.length, nextReviewDate: issues.map((issue) => issue.reviewDate).filter(Boolean).sort()[0] || "" }, sections: [
    { id: "important-notice", heading: "Important Report Notice", type: "notice", source: "structured", text: "Some explanatory sections in this report were generated with AI assistance from structured case data supplied to the report workflow. The content must be reviewed by a person before it is shared or treated as an approved statement." },
    { id: "at-a-glance", heading: "At a Glance", type: "metrics", source: "structured", metadata: { activeIssues: issues.filter((issue) => !["resolved", "archived"].includes(issue.status)).length, incidents: incidentRecords.length, evidence: evidenceRecords.length, documents: documentRecords.length, strategy: records.filter((record) => record.type === "strategy").length, watch: records.filter((record) => record.type === "watch").length, outstandingFindings: outstanding.length, nextReviewDate: issues.map((issue) => issue.reviewDate).filter(Boolean).sort()[0] || "Not recorded" }, narrative: hasNarrative ? { source: "ai_assisted", items: narrative.atAGlance || [] } : null },
    { id: "current-situation", heading: "Your Current Situation", type: "mixed", structured: { source: "structured", caseStatus: model.sourceCase?.status || "Not recorded" }, userAuthored: { source: "user_authored", items: issueRows.filter((issue) => issue.currentPosition).map((issue) => ({ issueLabel: issue.displayLabel, currentPosition: issue.currentPosition })) }, aiAssisted: narrative.yourSituation ? { source: "ai_assisted", text: narrative.yourSituation } : null },
    { id: "main-issues", heading: "Main Issues", type: "issues", source: "mixed", items: issueRows },
    { id: "chronology", heading: "What Has Happened", type: "chronology", source: "structured", groups: chronologyGroups.map((group) => ({ ...group, entries: (group.entries || []).slice(0, 8).map((entry) => ({ ...entry, issueLabel: issues.find((issue) => issue.name === entry.sequenceGroup)?.displayLabel || entry.sequenceGroup, recordReference: { type: entry.recordType, title: entry.title, recordId: entry.recordId } })) })) },
    { id: "supporting-material", heading: "Evidence and Documents", type: "overview", source: "structured", metadata: { evidenceCount: evidenceRecords.length, documentCount: documentRecords.length, incidentsWithLinkedEvidence: resolvedEvidenceLinks, unresolvedReferences: model.unresolvedReferences?.length || 0, missingAttachmentMetadata: findings.filter((finding) => /ATTACHMENT/.test(finding.code)).length }, items: evidenceRecords.slice(0, 6).concat(documentRecords.slice(0, 6)).map((record) => readableRef(record, issues)) },
    { id: "recorded-position", heading: "Current Recorded Position", type: "mixed", structured: { source: "structured", observations: [`${resolvedEvidenceLinks} of ${incidentRecords.length} recorded Incidents have resolved structured Evidence links.`, `${model.unresolvedReferences?.length || 0} structured reference(s) are unresolved.`, `${outstanding.length} warning or critical data-quality matter(s) are recorded.`] }, userAuthored: { source: "user_authored", items: issueRows.filter((issue) => issue.currentPosition).map((issue) => ({ issueLabel: issue.displayLabel, text: issue.currentPosition })) }, aiAssisted: (narrative.whatThisReportShows?.length || narrative.currentPosition) ? { source: "ai_assisted", items: [...(narrative.whatThisReportShows || []), ...(narrative.currentPosition ? [narrative.currentPosition] : [])] } : null },
    { id: "outstanding-matters", heading: "Outstanding Matters", type: "findings", source: "structured", items: outstanding },
    { id: "next-steps", heading: "Next Steps", type: "actions", source: "structured", items: nextActions },
    { id: "limitations", heading: "Important Limitations", type: "limitations", source: "structured", items: ["This report summarises information recorded in ProveIt and may not include every technical record.", "The absence of a record does not prove that an event did not occur.", "AI-assisted prose requires human review and is not automatically verified.", "This report is not legal advice or an official determination.", "Attachments are referenced by metadata unless supplied separately.", "The source revision identifies the case state used to prepare this document."] },
  ] });
  return { ...report, presentation: { purpose: "Explain what is happening in the case, what is recorded, the current position, and the next structured steps.", audience: "Client / case owner", scope: "Whole case", exclusions: "Summary report; attachment binaries and full technical schedules are not embedded.", completeness: "Summary", generatedAt, sourceRevision: model.sourceRevision?.fingerprint || "", documentStatus: narrativeMeta.approved === true ? "Final" : "Draft", confidentiality: options.confidentiality || "Confidential", version: options.version || "1.0", preparedBy: narrativeMeta.preparedBy || "", approvedBy: narrativeMeta.approvedBy || "", aiAssistance: hasNarrative ? "AI-assisted narrative requiring human review" : "No generated narrative included" }, narrativeMetadata: { source: hasNarrative ? "ai_assisted" : "structured", generatedAt: narrativeMeta.generatedAt || "", modelLabel: narrativeMeta.modelLabel || "", promptRevision: narrativeMeta.promptRevision || (hasNarrative ? CLIENT_REPORT_PROMPT_REVISION : ""), sourceRevision: narrativeMeta.sourceRevision || "", currentSourceRevision: model.sourceRevision?.fingerprint || "", revisionState, reviewed: narrativeMeta.reviewed === true, reviewedBy: narrativeMeta.reviewedBy || null, reviewedAt: narrativeMeta.reviewedAt || null, approved: narrativeMeta.approved === true, approvedBy: narrativeMeta.approvedBy || null, approvedAt: narrativeMeta.approvedAt || null }, recordReferences: records.map((record) => readableRef(record, issues)), appendices };
}
