import assert from "node:assert/strict";
import test from "node:test";
import { buildCaseReportModel } from "./reportModel.js";
import { getReportDefinition } from "./reportDefinitions.js";
import { validateReportDocument } from "./reportDocument.js";
import { buildManagementReportDocument } from "./managementReportDocument.js";

const generatedAt = "2026-08-02T12:00:00Z";
function fixture() { return { id: "case-1", name: "Heating case", status: "open", updatedAt: "2026-08-01", issues: [{ id: "issue-1", reference: "ISS-003", name: "Heating Failure", purpose: "Secure a repair response.", status: "waiting_response", priority: "high", ownerPartyId: "p1", reviewDate: "2026-08-01", currentPosition: "The repair response remains outstanding.", createdAt: "2026-01-01", updatedAt: "2026-08-01" }, { id: "issue-2", reference: "ISS-004", name: "Costs", status: "open", priority: "normal", createdAt: "2026-01-02", updatedAt: "2026-07-01" }], parties: [{ id: "p1", displayName: "Alex Tenant", role: "Tenant" }], incidents: [{ id: "i1", title: "Heating stopped", eventDate: "2026-07-20", createdAt: "2026-07-21", sequenceGroupId: "issue-1", sequenceGroup: "Heating Failure", linkedEvidenceIds: [] }], evidence: [{ id: "e1", title: "Photograph", date: "2026-07-20", createdAt: "2026-07-21", sequenceGroupId: "issue-1", sequenceGroup: "Heating Failure", functionSummary: "Records the temperature" }], documents: [], ledger: [{ id: "l1", label: "Heater cost", date: "2026-07-22", amount: 50, currency: "EUR", status: "pending", sequenceGroupId: "issue-2", sequenceGroup: "Costs" }], strategy: [{ id: "s1", title: "Request decision", createdAt: "2026-07-25", status: "pending", decisionStatus: "awaiting_approval", nextSteps: ["Approve repair request"], reviewDate: "2026-08-01", ownerPartyId: "p1", sequenceGroupId: "issue-1", sequenceGroup: "Heating Failure" }], watchItems: [{ id: "w1", title: "Monitor response", status: "monitoring", reviewDate: "2026-08-05", sequenceGroupId: "issue-1", sequenceGroup: "Heating Failure" }] }; }
function build(source = fixture()) { const model = buildCaseReportModel(source, { generatedAt, includeArchived: true, includeDiagnostics: true }); return buildManagementReportDocument(model, getReportDefinition("management"), { generatedAt }); }

test("builds a deterministic serialisable executive Management document without mutating input", () => { const source = fixture(); const before = structuredClone(source); const first = build(source); assert.deepEqual(first, build(source)); assert.deepEqual(source, before); assert.equal(validateReportDocument(first).valid, true); assert.doesNotThrow(() => JSON.stringify(first)); assert.equal(first.report.id, "management"); assert.equal(first.presentation.aiAssistance, "None"); });
test("orders major Issues by recorded priority and exposes human references without internal IDs", () => { const document = build(); const issues = document.sections.find((item) => item.id === "major-issues").items; assert.deepEqual(issues.map((item) => item.displayLabel), ["ISS-003 — Heating Failure", "ISS-004 — Costs"]); assert.equal(issues[0].currentPosition, "The repair response remains outstanding."); assert.doesNotMatch(document.summary.summaryText, /issue-1/); });
test("groups risks decisions and actions from deterministic structured sources", () => { const document = build(); const actions = document.sections.find((item) => item.id === "next-actions").groups; assert.equal(actions.find((item) => item.id === "overdue").items.length > 0, true); assert.equal(document.sections.find((item) => item.id === "management-decisions").items.some((item) => /strategy approval/i.test(item.decision)), true); assert.equal(document.sections.find((item) => item.id === "outstanding-matters").groups.length, 6); });
test("progress states the missing historical baseline and empty cases remain honest", () => { const document = build(); assert.match(document.sections.find((item) => item.id === "progress").metadata.limitation, /does not store a report-to-report review baseline/); const empty = build({ id: "empty", name: "Empty", incidents: [], evidence: [], documents: [], ledger: [], strategy: [], watchItems: [], issues: [] }); assert.equal(empty.summary.summaryText, "No management briefing records or Issues are available in this case."); assert.deepEqual(empty.sections.find((item) => item.id === "major-issues").items, []); });
