import { getReportDocumentSection } from "./reportDocument.js";

function safeText(value) {
  if (value == null) return "";
  if (["string", "number", "boolean"].includes(typeof value)) return String(value).replace(/data:[^\s)]+/gi, "[binary content omitted]");
  return JSON.stringify(value).replace(/data:[^\s)"}]+/gi, "[binary content omitted]");
}
function inline(value) { return safeText(value).replace(/\|/g, "\\|").replace(/\r?\n/g, "<br>").trim() || "-"; }
function list(items, render) { return items?.length ? items.map((item) => `- ${render(item)}`) : ["- None"]; }
function base(document) {
  const source = document.source || {}; const summary = document.summary || {};
  return [`# ${inline(document.report?.title || "Report")}`, "", "## Case Details", "", `- Case: ${inline(source.caseName || source.caseId)}`, `- Case ID: ${inline(source.caseId)}`, `- Status: ${inline(summary.caseOverview?.status)}`, `- Category: ${inline(summary.caseOverview?.category)}`, `- Generated: ${inline(document.report?.generatedAt)}`, `- Source revision: ${inline(source.sourceRevision?.fingerprint)}`, "", "## Report Scope", "", `- Scope: ${inline(source.scope?.type === "sequenceGroup" ? `Sequence Group: ${source.scope.sequenceGroupName || "-"}` : "Whole case")}`, `- Completeness: ${inline(document.report?.completeness)}`];
}
function appendNotices(lines, document) { lines.push("", "## Notices", "", ...list(document.notices || [], (item) => `${inline(item.code)}: ${inline(item.message)}`), ""); }

function evidence(document) {
  const lines = base(document); const rows = getReportDocumentSection(document, "evidence-schedule")?.rows || [];
  lines.push(`- Evidence records: ${inline(document.summary?.includedEvidenceCount ?? 0)}`, `- Incidents in primary scope: ${inline(document.summary?.scopedIncidentCount ?? 0)}`, `- Archived records: ${inline(document.summary?.archivedPolicy)}`, "", "## Evidence Schedule", "");
  if (!rows.length) lines.push("No evidence is included in this scope."); else { lines.push("| Evidence ID | Title | Date | Status | Verification | Role / Type | Function summary | Linked incidents | Attachments | Archived |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"); rows.forEach((row) => lines.push(`| ${inline(row.evidenceId)} | ${inline(row.title)} | ${inline(row.date)} | ${inline(row.status)} | ${inline(row.verificationState)} | ${inline(row.evidenceRole || row.evidenceType)} | ${inline(row.functionSummary)} | ${inline((row.linkedIncidentTitles || []).join(", "))} | ${inline((row.attachmentFilenames || []).join(", "))} | ${inline(row.archived ? "Yes" : "No")} |`)); }
  const incidents = getReportDocumentSection(document, "supported-incidents")?.items || []; const weak = getReportDocumentSection(document, "weak-unlinked-evidence")?.diagnostics || {}; const unresolved = getReportDocumentSection(document, "unresolved-references")?.items || [];
  lines.push("", "## Supported Incidents", "", ...list(incidents, (item) => `${inline(item.id)} — ${inline(item.title)} — evidence: ${inline((item.supportingEvidenceIds || []).join(", "))}`), "", "## Weak or Unlinked Evidence", "", "### Not linked to incidents", ...list(weak.unlinkedEvidence, (item) => `${inline(item.id)} — ${inline(item.title)}`), "", "### Missing function summary", ...list(weak.evidenceMissingFunctionSummary, (item) => `${inline(item.id)} — ${inline(item.title)}`), "", "### No attachments", ...list(weak.evidenceWithoutAttachments, (item) => `${inline(item.id)} — ${inline(item.title)}`), "", "## Unresolved References", "", ...list(unresolved, (item) => `${inline(item.sourceRecordType)} ${inline(item.sourceRecordId)} — ${inline(item.message)} — technical reference: ${inline(item.targetId)}`)); appendNotices(lines, document); lines.push("Attachments are metadata-only; attachment content is not embedded.", ""); return lines.join("\n");
}
function documents(document) {
  const lines = base(document); const rows = getReportDocumentSection(document, "document-schedule")?.rows || []; const context = getReportDocumentSection(document, "linked-incident-context"); const weak = getReportDocumentSection(document, "weak-incomplete-documents")?.diagnostics || {}; const unresolved = getReportDocumentSection(document, "unresolved-references")?.items || [];
  lines.push(`- Documents: ${inline(document.summary?.includedDocumentCount ?? 0)}`, `- Archived documents: ${inline(document.summary?.archivedDocumentCount ?? 0)}`, "", "## Document Schedule", "");
  if (!rows.length) lines.push("No documents are included in this scope."); else { lines.push("| Document ID | Title | Date | Type | Status | Summary | Source / Author | Sequence Group | Linked incidents | Linked evidence | Attachments | Archived |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"); rows.forEach((row) => lines.push(`| ${inline(row.documentId)} | ${inline(row.title)} | ${inline(row.documentDate || row.date)} | ${inline(row.documentType || row.category)} | ${inline(row.status)} | ${inline(row.summary || row.notes || row.functionSummary)} | ${inline([row.source, row.author].filter(Boolean).join(" / "))} | ${inline(row.sequenceGroup)} | ${inline((row.linkedIncidents || []).map((item) => item.title).join(", "))} | ${inline((row.linkedEvidence || []).map((item) => item.title).join(", "))} | ${inline((row.attachmentNames || []).join(", "))} | ${inline(row.archived ? "Yes" : "No")} |`)); }
  lines.push("", "## Linked Incident Context", "", ...list(context?.items, (item) => `${inline(item.id)} — ${inline(item.title)} — documents: ${inline((item.documents || []).map((doc) => doc.title).join(", "))}`), "", "## Weak or Incomplete Documents", "", "### Unlinked", ...list(weak.unlinkedDocuments, (item) => `${inline(item.id)} — ${inline(item.title)}`), "", "### Missing summary", ...list(weak.documentsMissingSummary, (item) => `${inline(item.id)} — ${inline(item.title)}`), "", "## Unresolved References", "", ...list(unresolved, (item) => `${inline(item.sourceRecordType)} ${inline(item.sourceRecordId)} — ${inline(item.message)}`)); appendNotices(lines, document); return lines.join("\n");
}
function ledger(document) {
  const lines = base(document); const rows = getReportDocumentSection(document, "ledger-schedule")?.rows || []; const totals = getReportDocumentSection(document, "totals-exclusions"); const weak = getReportDocumentSection(document, "weak-incomplete-ledger")?.diagnostics || {}; const unresolved = getReportDocumentSection(document, "unresolved-references")?.items || [];
  lines.push(`- Ledger entries: ${inline(document.summary?.includedLedgerCount ?? 0)}`, `- Monetary entries: ${inline(document.summary?.monetaryEntryCount ?? 0)}`, `- Excluded status notes: ${inline(document.summary?.excludedStatusNoteCount ?? 0)}`, "", "## Ledger Summary", "", ...list(document.summary?.totalsByCurrency, (item) => `${inline(item.currency)}: total ${inline(item.total)}, credits ${inline(item.credit)}, debits ${inline(item.debit)}, disputed ${inline(item.disputed)}, pending ${inline(item.pending)}, waived ${inline(item.waived)}`), "", "## Ledger Schedule", "");
  if (!rows.length) lines.push("No ledger entries are included in this scope."); else { lines.push("| Ledger ID | Title | Date | Type | Status | Amount | Currency | Sequence Group | Proof | Linked records | Archived |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"); rows.forEach((row) => lines.push(`| ${inline(row.ledgerId)} | ${inline(row.title)} | ${inline(row.date)} | ${inline([row.type, row.subType].filter(Boolean).join(" / "))} | ${inline(row.status)} | ${inline(row.amount)} | ${inline(row.currency)} | ${inline(row.sequenceGroup)} | ${inline(row.proofType || row.proofStatus)} | ${inline((row.linkedRecords || []).map((item) => item.title).join(", "))} | ${inline(row.archived ? "Yes" : "No")} |`)); }
  lines.push("", "## Totals and Exclusions", "", ...list(totals?.items, (item) => `${inline(item.currency)} — total ${inline(item.total)} (no currency conversion)`), "", "## Weak or Incomplete Ledger Entries", "", "### Missing amount", ...list(weak.missingAmount, (item) => `${inline(item.id || item.ledgerId)} — ${inline(item.title)}`), "", "### Missing proof", ...list(weak.entriesWithMissingProof, (item) => `${inline(item.id || item.ledgerId)} — ${inline(item.title)}`), "", "## Unresolved References", "", ...list(unresolved, (item) => `${inline(item.sourceRecordType)} ${inline(item.sourceRecordId)} — ${inline(item.message)}`)); appendNotices(lines, document); return lines.join("\n");
}

function incidentSchedule(document) {
  const lines = base(document); const summary = document.summary || {}; const rows = getReportDocumentSection(document, "incident-schedule")?.rows || []; const coverage = getReportDocumentSection(document, "evidence-coverage")?.rows || []; const findings = getReportDocumentSection(document, "incident-quality-findings")?.items || []; const unresolved = getReportDocumentSection(document, "unresolved-references")?.items || [];
  lines.push("", "## Summary", "", `- Incidents: ${inline(summary.scopedIncidentCount || 0)}`, `- Active: ${inline(summary.activeIncidentCount || 0)}`, `- Archived: ${inline(summary.archivedIncidentCount || 0)}`, `- With linked evidence: ${inline(summary.incidentsWithLinkedEvidence || 0)}`, `- Without linked evidence: ${inline(summary.incidentsWithoutLinkedEvidence || 0)}`, "", "## Incident Schedule", "");
  if (!rows.length) lines.push("No incidents are included in this report scope."); else { lines.push("| Incident ID | Title | Event date | Logged date | Date status | Status | Type | Description | Outcome | Sequence Group | Parties | Evidence | Documents | Strategy | To Watch | Ledger | Attachments | Archived |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"); rows.forEach((row) => lines.push(`| ${inline(row.incidentId)} | ${inline(row.title)} | ${inline(row.eventDate)} | ${inline(row.loggedDate)} | ${inline(row.dateStatus)} | ${inline(row.status)} | ${inline(row.category)} | ${inline(row.description || row.functionSummary)} | ${inline(row.outcome)} | ${inline(row.sequenceGroup)} | ${inline((row.resolvedParties || []).map((party) => `${party.name}${party.role ? ` (${party.role})` : ""}`).join(", "))} | ${inline((row.linkedEvidence || []).map((item) => `${item.id}: ${item.title}`).join(", "))} | ${inline((row.linkedDocuments || []).map((item) => `${item.id}: ${item.title}`).join(", "))} | ${inline((row.linkedStrategies || []).map((item) => `${item.id}: ${item.title}`).join(", "))} | ${inline((row.linkedWatch || []).map((item) => `${item.id}: ${item.title}`).join(", "))} | ${inline((row.linkedLedger || []).map((item) => `${item.id}: ${item.title}`).join(", "))} | ${inline((row.attachmentFilenames || []).join(", "))} | ${inline(row.archived ? "Yes" : "No")} |`)); }
  lines.push("", "## Evidence Coverage", "", ...list(coverage, (item) => `${inline(item.incidentId)} — ${inline(item.incidentTitle)} — ${inline(item.coverageStatus)} — evidence: ${inline((item.supportingEvidenceIds || []).join(", "))}`), "", "## Weak or Incomplete Incidents", "", ...list(findings, (item) => `${inline(item.code)} — ${inline(item.recordId)} — ${inline(item.message)}`), "", "## Unresolved References", "", ...list(unresolved, (item) => `${inline(item.sourceRecordId)} — ${inline(item.message)} — technical reference: ${inline(item.targetId)}`)); appendNotices(lines, document); lines.push("## Source Revision", "", inline(document.source?.sourceRevision?.fingerprint), ""); return lines.join("\n");
}

function chronology(document) {
  const lines = base(document); const summary = document.summary || {}; const totals = getReportDocumentSection(document, "record-type-totals")?.metadata || {}; const groups = getReportDocumentSection(document, "chronology")?.groups || [];
  lines.push("", "## Summary", "", `- Entries: ${inline(summary.totalChronologyEntries || 0)}`, `- Valid dates: ${inline(summary.validDateCount || 0)}`, `- Malformed dates: ${inline(summary.malformedDateCount || 0)}`, `- Missing dates: ${inline(summary.missingDateCount || 0)}`, `- Earliest valid date: ${inline(summary.earliestValidDate)}`, `- Latest valid date: ${inline(summary.latestValidDate)}`, "", "## Record Type Totals", "", ...Object.entries(totals).map(([type, count]) => `- ${inline(type)}: ${inline(count)}`), "", "## Chronology", "");
  if (!groups.length) lines.push("No chronology entries are included in this report scope.");
  groups.forEach((group) => { lines.push(`### ${inline(group.label)}`, ""); lines.push(...list(group.entries, (entry) => `${inline(entry.dateStatus === "valid" ? entry.date : entry.dateStatus === "malformed" ? `Malformed: ${entry.originalDate || entry.date}` : "Missing date")} — ${inline(entry.recordType)} ${inline(entry.recordId)} — ${inline(entry.title)}${entry.summary ? ` — ${inline(entry.summary)}` : ""}`), ""); });
  appendNotices(lines, document); lines.push("## Source Revision", "", inline(document.source?.sourceRevision?.fingerprint), ""); return lines.join("\n");
}

export function formatReportDocumentAsMarkdown(reportDocument = {}) {
  if (reportDocument.report?.id === "evidence") return evidence(reportDocument);
  if (reportDocument.report?.id === "document") return documents(reportDocument);
  if (reportDocument.report?.id === "ledger") return ledger(reportDocument);
  if (reportDocument.report?.id === "incidentSchedule") return incidentSchedule(reportDocument);
  if (reportDocument.report?.id === "chronologyReport") return chronology(reportDocument);
  throw new Error(`Markdown output is not supported for report "${reportDocument.report?.id || "unknown"}".`);
}
