import { getReportDocumentSection } from "./reportDocument.js";

function safeText(value) {
  if (value == null) return "";
  if (["string", "number", "boolean"].includes(typeof value)) return String(value).replace(/data:[^\s)]+/gi, "[binary content omitted]");
  return JSON.stringify(value).replace(/data:[^\s)"}]+/gi, "[binary content omitted]");
}
function inline(value) { return safeText(value).replace(/\|/g, "\\|").replace(/\r?\n/g, "<br>").trim() || "-"; }
function list(items, render) { return items?.length ? items.map((item) => `- ${render(item)}`) : ["- None"]; }
function base(document) {
  const source = document.source || {}; const summary = document.summary || {};
  return [`# ${inline(document.report?.title || "Report")}`, "", "## Case Details", "", `- Case: ${inline(source.caseName || source.caseId)}`, `- Case ID: ${inline(source.caseId)}`, `- Status: ${inline(summary.caseOverview?.status)}`, `- Category: ${inline(summary.caseOverview?.category)}`, `- Generated: ${inline(document.report?.generatedAt)}`, `- Source revision: ${inline(source.sourceRevision?.fingerprint)}`, "", "## Report Scope", "", `- Scope: ${inline(source.scope?.type === "sequenceGroup" ? `Sequence Group: ${source.scope.sequenceGroupName || "-"}` : "Whole case")}`, `- Completeness: ${inline(document.report?.completeness)}`];
}
function appendNotices(lines, document) { lines.push("", "## Notices", "", ...list(document.notices || [], (item) => `${inline(item.code)}: ${inline(item.message)}`), ""); }

function evidence(document) {
  const lines = base(document); const rows = getReportDocumentSection(document, "evidence-schedule")?.rows || [];
  lines.push(`- Evidence records: ${inline(document.summary?.includedEvidenceCount ?? 0)}`, `- Incidents in primary scope: ${inline(document.summary?.scopedIncidentCount ?? 0)}`, `- Archived records: ${inline(document.summary?.archivedPolicy)}`, "", "## Evidence Schedule", "");
  if (!rows.length) lines.push("No evidence is included in this scope."); else { lines.push("| Evidence ID | Title | Date | Status | Verification | Role / Type | Function summary | Linked incidents | Attachments | Archived |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"); rows.forEach((row) => lines.push(`| ${inline(row.evidenceId)} | ${inline(row.title)} | ${inline(row.date)} | ${inline(row.status)} | ${inline(row.verificationState)} | ${inline(row.evidenceRole || row.evidenceType)} | ${inline(row.functionSummary)} | ${inline((row.linkedIncidentTitles || []).join(", "))} | ${inline((row.attachmentFilenames || []).join(", "))} | ${inline(row.archived ? "Yes" : "No")} |`)); }
  const incidents = getReportDocumentSection(document, "supported-incidents")?.items || []; const weak = getReportDocumentSection(document, "weak-unlinked-evidence")?.diagnostics || {}; const unresolved = getReportDocumentSection(document, "unresolved-references")?.items || [];
  lines.push("", "## Supported Incidents", "", ...list(incidents, (item) => `${inline(item.id)} — ${inline(item.title)} — evidence: ${inline((item.supportingEvidenceIds || []).join(", "))}`), "", "## Weak or Unlinked Evidence", "", "### Not linked to incidents", ...list(weak.unlinkedEvidence, (item) => `${inline(item.id)} — ${inline(item.title)}`), "", "### Missing function summary", ...list(weak.evidenceMissingFunctionSummary, (item) => `${inline(item.id)} — ${inline(item.title)}`), "", "### No attachments", ...list(weak.evidenceWithoutAttachments, (item) => `${inline(item.id)} — ${inline(item.title)}`), "", "## Unresolved References", "", ...list(unresolved, (item) => `${inline(item.sourceRecordType)} ${inline(item.sourceRecordId)} — ${inline(item.message)} — technical reference: ${inline(item.targetId)}`)); appendNotices(lines, document); lines.push("Attachments are metadata-only; attachment content is not embedded.", ""); return lines.join("\n");
}
function documents(document) {
  const lines = base(document); const rows = getReportDocumentSection(document, "document-schedule")?.rows || []; const context = getReportDocumentSection(document, "linked-incident-context"); const weak = getReportDocumentSection(document, "weak-incomplete-documents")?.diagnostics || {}; const unresolved = getReportDocumentSection(document, "unresolved-references")?.items || [];
  lines.push(`- Documents: ${inline(document.summary?.includedDocumentCount ?? 0)}`, `- Archived documents: ${inline(document.summary?.archivedDocumentCount ?? 0)}`, "", "## Document Schedule", "");
  if (!rows.length) lines.push("No documents are included in this scope."); else { lines.push("| Document ID | Title | Date | Type | Status | Summary | Source / Author | Sequence Group | Linked incidents | Linked evidence | Attachments | Archived |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"); rows.forEach((row) => lines.push(`| ${inline(row.documentId)} | ${inline(row.title)} | ${inline(row.documentDate || row.date)} | ${inline(row.documentType || row.category)} | ${inline(row.status)} | ${inline(row.summary || row.notes || row.functionSummary)} | ${inline([row.source, row.author].filter(Boolean).join(" / "))} | ${inline(row.sequenceGroup)} | ${inline((row.linkedIncidents || []).map((item) => item.title).join(", "))} | ${inline((row.linkedEvidence || []).map((item) => item.title).join(", "))} | ${inline((row.attachmentNames || []).join(", "))} | ${inline(row.archived ? "Yes" : "No")} |`)); }
  lines.push("", "## Linked Incident Context", "", ...list(context?.items, (item) => `${inline(item.id)} — ${inline(item.title)} — documents: ${inline((item.documents || []).map((doc) => doc.title).join(", "))}`), "", "## Weak or Incomplete Documents", "", "### Unlinked", ...list(weak.unlinkedDocuments, (item) => `${inline(item.id)} — ${inline(item.title)}`), "", "### Missing summary", ...list(weak.documentsMissingSummary, (item) => `${inline(item.id)} — ${inline(item.title)}`), "", "## Unresolved References", "", ...list(unresolved, (item) => `${inline(item.sourceRecordType)} ${inline(item.sourceRecordId)} — ${inline(item.message)}`)); appendNotices(lines, document); return lines.join("\n");
}
function ledger(document) {
  const lines = base(document); const rows = getReportDocumentSection(document, "ledger-schedule")?.rows || []; const totals = getReportDocumentSection(document, "totals-exclusions"); const weak = getReportDocumentSection(document, "weak-incomplete-ledger")?.diagnostics || {}; const unresolved = getReportDocumentSection(document, "unresolved-references")?.items || [];
  lines.push(`- Ledger entries: ${inline(document.summary?.includedLedgerCount ?? 0)}`, `- Monetary entries: ${inline(document.summary?.monetaryEntryCount ?? 0)}`, `- Excluded status notes: ${inline(document.summary?.excludedStatusNoteCount ?? 0)}`, "", "## Ledger Summary", "", ...list(document.summary?.totalsByCurrency, (item) => `${inline(item.currency)}: total ${inline(item.total)}, credits ${inline(item.credit)}, debits ${inline(item.debit)}, disputed ${inline(item.disputed)}, pending ${inline(item.pending)}, waived ${inline(item.waived)}`), "", "## Ledger Schedule", "");
  if (!rows.length) lines.push("No ledger entries are included in this scope."); else { lines.push("| Ledger ID | Title | Date | Type | Status | Amount | Currency | Sequence Group | Proof | Linked records | Archived |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"); rows.forEach((row) => lines.push(`| ${inline(row.ledgerId)} | ${inline(row.title)} | ${inline(row.date)} | ${inline([row.type, row.subType].filter(Boolean).join(" / "))} | ${inline(row.status)} | ${inline(row.amount)} | ${inline(row.currency)} | ${inline(row.sequenceGroup)} | ${inline(row.proofType || row.proofStatus)} | ${inline((row.linkedRecords || []).map((item) => item.title).join(", "))} | ${inline(row.archived ? "Yes" : "No")} |`)); }
  lines.push("", "## Totals and Exclusions", "", ...list(totals?.items, (item) => `${inline(item.currency)} — total ${inline(item.total)} (no currency conversion)`), "", "## Weak or Incomplete Ledger Entries", "", "### Missing amount", ...list(weak.missingAmount, (item) => `${inline(item.id || item.ledgerId)} — ${inline(item.title)}`), "", "### Missing proof", ...list(weak.entriesWithMissingProof, (item) => `${inline(item.id || item.ledgerId)} — ${inline(item.title)}`), "", "## Unresolved References", "", ...list(unresolved, (item) => `${inline(item.sourceRecordType)} ${inline(item.sourceRecordId)} — ${inline(item.message)}`)); appendNotices(lines, document); return lines.join("\n");
}

function incidentSchedule(document) {
  const lines = base(document); const summary = document.summary || {}; const rows = getReportDocumentSection(document, "incident-schedule")?.rows || []; const coverage = getReportDocumentSection(document, "evidence-coverage")?.rows || []; const findings = getReportDocumentSection(document, "incident-quality-findings")?.items || []; const unresolved = getReportDocumentSection(document, "unresolved-references")?.items || [];
  lines.push("", "## Summary", "", `- Incidents: ${inline(summary.scopedIncidentCount || 0)}`, `- Active: ${inline(summary.activeIncidentCount || 0)}`, `- Archived: ${inline(summary.archivedIncidentCount || 0)}`, `- With linked evidence: ${inline(summary.incidentsWithLinkedEvidence || 0)}`, `- Without linked evidence: ${inline(summary.incidentsWithoutLinkedEvidence || 0)}`, "", "## Incident Schedule", "");
  if (!rows.length) lines.push("No incidents are included in this report scope."); else { lines.push("| Incident ID | Title | Event date | Logged date | Date status | Status | Type | Description | Outcome | Sequence Group | Parties | Evidence | Documents | Strategy | To Watch | Ledger | Attachments | Archived |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"); rows.forEach((row) => lines.push(`| ${inline(row.incidentId)} | ${inline(row.title)} | ${inline(row.eventDate)} | ${inline(row.loggedDate)} | ${inline(row.dateStatus)} | ${inline(row.status)} | ${inline(row.category)} | ${inline(row.description || row.functionSummary)} | ${inline(row.outcome)} | ${inline(row.sequenceGroup)} | ${inline((row.resolvedParties || []).map((party) => `${party.name}${party.role ? ` (${party.role})` : ""}`).join(", "))} | ${inline((row.linkedEvidence || []).map((item) => `${item.id}: ${item.title}`).join(", "))} | ${inline((row.linkedDocuments || []).map((item) => `${item.id}: ${item.title}`).join(", "))} | ${inline((row.linkedStrategies || []).map((item) => `${item.id}: ${item.title}`).join(", "))} | ${inline((row.linkedWatch || []).map((item) => `${item.id}: ${item.title}`).join(", "))} | ${inline((row.linkedLedger || []).map((item) => `${item.id}: ${item.title}`).join(", "))} | ${inline((row.attachmentFilenames || []).join(", "))} | ${inline(row.archived ? "Yes" : "No")} |`)); }
  lines.push("", "## Evidence Coverage", "", ...list(coverage, (item) => `${inline(item.incidentId)} — ${inline(item.incidentTitle)} — ${inline(item.coverageStatus)} — evidence: ${inline((item.supportingEvidenceIds || []).join(", "))}`), "", "## Weak or Incomplete Incidents", "", ...list(findings, (item) => `${inline(item.code)} — ${inline(item.recordId)} — ${inline(item.message)}`), "", "## Unresolved References", "", ...list(unresolved, (item) => `${inline(item.sourceRecordId)} — ${inline(item.message)} — technical reference: ${inline(item.targetId)}`)); appendNotices(lines, document); lines.push("## Source Revision", "", inline(document.source?.sourceRevision?.fingerprint), ""); return lines.join("\n");
}

function chronology(document) {
  const lines = base(document); const summary = document.summary || {}; const totals = getReportDocumentSection(document, "record-type-totals")?.metadata || {}; const groups = getReportDocumentSection(document, "chronology")?.groups || [];
  lines.push("", "## Summary", "", `- Entries: ${inline(summary.totalChronologyEntries || 0)}`, `- Valid dates: ${inline(summary.validDateCount || 0)}`, `- Malformed dates: ${inline(summary.malformedDateCount || 0)}`, `- Missing dates: ${inline(summary.missingDateCount || 0)}`, `- Earliest valid date: ${inline(summary.earliestValidDate)}`, `- Latest valid date: ${inline(summary.latestValidDate)}`, "", "## Record Type Totals", "", ...Object.entries(totals).map(([type, count]) => `- ${inline(type)}: ${inline(count)}`), "", "## Chronology", "");
  if (!groups.length) lines.push("No chronology entries are included in this report scope.");
  groups.forEach((group) => { lines.push(`### ${inline(group.label)}`, ""); lines.push(...list(group.entries, (entry) => `${inline(entry.dateStatus === "valid" ? entry.date : entry.dateStatus === "malformed" ? `Malformed: ${entry.originalDate || entry.date}` : "Missing date")} — ${inline(entry.recordType)} ${inline(entry.recordId)} — ${inline(entry.title)}${entry.summary ? ` — ${inline(entry.summary)}` : ""}`), ""); });
  appendNotices(lines, document); lines.push("## Source Revision", "", inline(document.source?.sourceRevision?.fingerprint), ""); return lines.join("\n");
}

function caseAudit(document) {
  const lines = base(document); const summary = document.summary || {}; const findings = getReportDocumentSection(document, "findings-by-severity")?.items || []; const categories = getReportDocumentSection(document, "findings-by-category")?.categories || []; const unresolved = getReportDocumentSection(document, "unresolved-references")?.items || [];
  lines.push("", "## Audit Status", "", inline(summary.auditStatus), "", "This status reflects deterministic structured data-quality rules and is not a legal or factual conclusion.", "", "## Summary", "", `- Total findings: ${inline(summary.totalFindings || 0)}`, `- Critical: ${inline(summary.critical || 0)}`, `- Warnings: ${inline(summary.warning || 0)}`, `- Information: ${inline(summary.information || 0)}`, `- Affected records: ${inline(summary.affectedRecordCount || 0)}`, `- Unaffected records: ${inline(summary.unaffectedRecordCount || 0)}`, `- Unresolved references: ${inline(summary.unresolvedReferenceCount || 0)}`);
  for (const [severity, heading] of [["critical", "Critical Findings"], ["warning", "Warnings"], ["information", "Informational Findings"]]) lines.push("", `## ${heading}`, "", ...list(findings.filter((item) => item.severity === severity), (item) => `${inline(item.code)} — ${inline(item.recordType)} ${inline(item.recordId)} — ${inline(item.message)}`));
  lines.push("", "## Findings by Category", ""); categories.forEach((category) => lines.push(`### ${inline(category.label)}`, "", ...list(category.findings, (item) => `${inline(item.severity)} — ${inline(item.code)} — ${inline(item.recordType)} ${inline(item.recordId)} — ${inline(item.message)}`), ""));
  lines.push("## Unresolved References", "", ...list(unresolved, (item) => `${inline(item.sourceRecordType)} ${inline(item.sourceRecordId)} — ${inline(item.message)} — technical reference: ${inline(item.targetId)}`)); appendNotices(lines, document); lines.push("## Source Revision", "", inline(document.source?.sourceRevision?.fingerprint), ""); return lines.join("\n");
}

function investigation(document) {
  const lines = [`# ${inline(document.report?.title || "Investigation Report")}`, "", "## Document Control", ""];
  const presentation = document.presentation || {}; const summary = document.summary || {};
  for (const [label, value] of [["Case", document.source?.caseName || document.source?.caseId], ["Issue", summary.issue?.displayLabel], ["Purpose", presentation.purpose], ["Audience", presentation.audience], ["Scope", presentation.scope], ["Reporting period", presentation.reportingPeriod], ["Exclusions / limitations", presentation.exclusions], ["Completeness", presentation.completeness], ["Generated", document.report?.generatedAt], ["Source revision", document.source?.sourceRevision?.fingerprint], ["Version", presentation.version], ["Document status", presentation.documentStatus], ["Confidentiality", presentation.confidentiality], ["AI assistance", presentation.aiAssistance]]) if (value) lines.push(`- ${label}: ${inline(value)}`);
  const narrative = (id) => getReportDocumentSection(document, id) || {};
  lines.push("", "## Executive Summary", "", safeText(narrative("executive-summary").text || summary.summaryText), "");
  const current = narrative("current-position").metadata || {};
  lines.push("## Current Position", "", ...(summary.issue ? [`- Issue: ${inline(summary.issue.displayLabel)}`, `- Status: ${inline(current.status)}`, `- Priority: ${inline(current.priority)}`, `- Owner: ${inline(current.ownerName)}`, `- Review date: ${inline(current.reviewDate)}`, `- Purpose: ${inline(current.purpose)}`, "", "User-authored current position:", "", safeText(current.currentPosition) || "No user-authored current position is recorded."] : ["No reliable whole-case current focus is available in the presentation-safe report model."]), "");
  const stats = narrative("snapshot").metadata || {};
  lines.push("## Investigation Snapshot", "", ...Object.entries(stats).map(([key, value]) => `- ${inline(key)}: ${inline(value)}`), "", "## Key Findings", "", ...list(narrative("key-findings").items, (item) => inline(item.text)), "", "## Narrative Chronology", "");
  (narrative("narrative-chronology").groups || []).forEach((group) => { lines.push(`### ${inline(group.label)}`, "", ...list(group.entries, (entry) => `${inline(entry.dateStatus === "valid" ? entry.date : entry.dateStatus)} — ${inline(entry.recordType)}: ${inline(entry.title)}${entry.summary ? ` — ${inline(entry.summary)}` : ""}`), ""); });
  for (const [id, heading] of [["evidence-overview", "Evidence Overview"], ["supporting-documents", "Supporting Documents"]]) { const value = narrative(id); lines.push(`## ${heading}`, "", ...Object.entries(value.metadata || {}).filter(([, item]) => !Array.isArray(item)).map(([key, item]) => `- ${inline(key)}: ${inline(item)}`), "", ...list(value.items, (item) => `${inline(item.title)}${item.functionSummary || item.summary ? ` — ${inline(item.functionSummary || item.summary)}` : ""} (${inline(item.id)})`), ""); }
  const financial = narrative("financial-position"); if (financial.id) lines.push("## Financial / Ledger Position", "", ...list(financial.metadata?.totalsByCurrency, (item) => `${inline(item.currency)} — total ${inline(item.total)}; credit ${inline(item.credit)}; debit ${inline(item.debit)}; pending ${inline(item.pending)}; disputed ${inline(item.disputed)}; waived ${inline(item.waived)}`), "");
  lines.push("## People Involved", "", ...list(narrative("people-involved").items, (item) => `${inline(item.name)} — ${inline([item.role, item.organisation].filter(Boolean).join(" / "))} — ${inline(item.directRecordAppearances)} direct record appearance(s)`), "", "## Outstanding Matters", "");
  (narrative("outstanding-matters").groups || []).forEach((group) => lines.push(`### ${inline(group.label)}`, "", ...list(group.items, (item) => `${inline(item.message || item.text)}${item.recordId ? ` — ${inline(item.title || item.recordId)} (${inline(item.recordId)})` : ""}`), ""));
  const actions = narrative("next-actions"); lines.push("## Next Actions", "", "### Case actions", "", ...list(actions.items, (item) => `${inline(item.action)} — source: ${inline(item.sourceType)} / ${inline(item.sourceTitle)}${item.owner ? ` — owner: ${inline(item.owner)}` : ""}${item.dueDate ? ` — due: ${inline(item.dueDate)}` : ""}`), "", "### Data-quality remediation", "", ...list(actions.metadata?.dataQualityRemediation, (item) => `${inline(item.message)} — ${inline(item.title || item.recordId)} (${inline(item.recordId)})`), "", "## Appendices", "");
  (document.appendices || []).forEach((appendix) => { lines.push(`### ${inline(appendix.label)} — ${inline(appendix.title)}`, ""); if (appendix.groups) appendix.groups.forEach((group) => lines.push(`#### ${inline(group.label)}`, ...list(group.entries, (entry) => `${inline(entry.date || entry.dateStatus)} — ${inline(entry.recordType)}: ${inline(entry.title)} (${inline(entry.recordId)})`), "")); else if (appendix.rows) lines.push(...list(appendix.rows, (row) => `${inline(row.title)} (${inline(row.incidentId || row.evidenceId || row.documentId || row.ledgerId)})`), ""); else lines.push(...list(appendix.items, (item) => `${inline(item.message || item.title)} (${inline(item.recordId || item.id)})`), ""); });
  appendNotices(lines, document); return lines.join("\n");
}

function management(document) {
  const lines = [`# ${inline(document.report?.title || "Management Report")}`, "", "## Document Control", ""]; const presentation = document.presentation || {};
  for (const [label, value] of [["Case", document.source?.caseName || document.source?.caseId], ["Purpose", presentation.purpose], ["Audience", presentation.audience], ["Scope", presentation.scope], ["Completeness", presentation.completeness], ["Generated", document.report?.generatedAt], ["Source revision", document.source?.sourceRevision?.fingerprint], ["Version", presentation.version], ["Document status", presentation.documentStatus], ["Confidentiality", presentation.confidentiality], ["AI assistance", presentation.aiAssistance]]) if (value) lines.push(`- ${label}: ${inline(value)}`);
  const value = (id) => getReportDocumentSection(document, id) || {};
  lines.push("", "## Executive Summary", "", safeText(value("executive-summary").text), "", "## Current Position", "", `- Case status: ${inline(value("current-position").metadata?.caseStatus)}`, "", "User-authored Issue positions:", "", ...list(value("current-position").items, (item) => `${inline(item.displayLabel)} — ${inline(item.currentPosition || item.purpose)} — status: ${inline(item.status)} — priority: ${inline(item.priority)}`), "", "## Management Snapshot", "", ...Object.entries(value("management-snapshot").metadata || {}).map(([key, item]) => `- ${inline(key)}: ${inline(item)}`), "", "## Major Issues", "", ...list(value("major-issues").items, (item) => `${inline(item.displayLabel)} — ${inline(item.priority)} / ${inline(item.status)} — owner: ${inline(item.owner)} — review: ${inline(item.reviewDate)} — ${inline(item.currentPosition || item.purpose)}`), "", "## Current Risks", "", ...list(value("current-risks").items, (item) => `${inline(item.message)} — ${inline(item.title || item.recordId)}${item.recordId ? ` (${inline(item.recordId)})` : ""}`), "", "## Progress Since Previous Review", "", safeText(value("progress").metadata?.limitation), "", ...list(value("progress").items, (item) => `${inline(item.loggedDate)} — ${inline(item.type)}: ${inline(item.title)}`), "", "## Outstanding Matters", "");
  (value("outstanding-matters").groups || []).forEach((group) => lines.push(`### ${inline(group.label)}`, "", ...list(group.items, (item) => `${inline(item.message || item.action)}${item.dueDate ? ` — due ${inline(item.dueDate)}` : ""}`), ""));
  lines.push("## Management Decisions Required", "", ...list(value("management-decisions").items, (item) => `${inline(item.decision)}${item.dueDate ? ` — due ${inline(item.dueDate)}` : ""}`), "", "## Next Actions", "");
  (value("next-actions").groups || []).forEach((group) => lines.push(`### ${inline(group.label)}`, "", ...list(group.items, (item) => `${inline(item.action)} — ${inline(item.source)}${item.owner ? ` — owner: ${inline(item.owner)}` : ""}${item.dueDate ? ` — due: ${inline(item.dueDate)}` : ""}`), ""));
  lines.push("## Appendices", ""); (document.appendices || []).forEach((appendix) => lines.push(`### ${inline(appendix.label)} — ${inline(appendix.title)}`, "", ...list(appendix.items || [], (item) => `${inline(item.displayLabel || item.message || item.title)}${item.recordId ? ` (${inline(item.recordId)})` : ""}`), "")); appendNotices(lines, document); return lines.join("\n");
}

export function formatReportDocumentAsMarkdown(reportDocument = {}) {
  if (reportDocument.report?.id === "management") return management(reportDocument);
  if (reportDocument.report?.id === "investigation") return investigation(reportDocument);
  if (reportDocument.report?.id === "evidence") return evidence(reportDocument);
  if (reportDocument.report?.id === "document") return documents(reportDocument);
  if (reportDocument.report?.id === "ledger") return ledger(reportDocument);
  if (reportDocument.report?.id === "incidentSchedule") return incidentSchedule(reportDocument);
  if (reportDocument.report?.id === "chronologyReport") return chronology(reportDocument);
  if (reportDocument.report?.id === "caseAudit") return caseAudit(reportDocument);
  throw new Error(`Markdown output is not supported for report "${reportDocument.report?.id || "unknown"}".`);
}
