const surface = "rounded-2xl border border-neutral-200 bg-neutral-50 p-4 dark:border-neutral-700 dark:bg-neutral-900";
const nested = "rounded-xl border border-neutral-200 bg-white p-3 dark:border-neutral-700 dark:bg-neutral-950";
const button = "min-h-11 rounded-xl border border-lime-500 bg-white px-3 py-2 text-sm font-semibold text-neutral-800 shadow-sm transition-colors hover:bg-lime-400/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-500 dark:bg-neutral-950 dark:text-neutral-100";
const muted = "text-sm text-neutral-600 dark:text-neutral-300";

function dateLabel(value) {
  if (!value) return "Not recorded";
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? value : new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(parsed);
}

function Section({ title, children, className = "" }) {
  return <section className={`${surface} min-w-0 ${className}`}><h2 className="text-lg font-semibold text-neutral-950 dark:text-neutral-100">{title}</h2>{children}</section>;
}

export default function CaseBriefingDashboard({ model, onOpenIssue, onOpenItem, onOpenTab, onAddIncident, onAddEvidence, onAddDocument, onOpenFullBriefing }) {
  const { snapshot, currentFocus, issues, attentionItems, nextActions, recentActivity, recommendedAction } = model;
  const act = (item) => item ? onOpenItem?.(item) : undefined;
  return (
    <main className="space-y-5" aria-labelledby="case-briefing-heading">
      <div><p className="text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">Overview</p><h1 id="case-briefing-heading" className="mt-1 text-2xl font-semibold text-neutral-950 dark:text-neutral-100">Case Briefing</h1><p className={`mt-1 ${muted}`}>A factual daily view of this case, its Issues, and recorded next steps.</p></div>
      {model.isEmptyCase && <div className={`${surface} border-lime-300`}><h2 className="text-lg font-semibold dark:text-white">Start building this case</h2><p className={`mt-1 ${muted}`}>Add the people involved, record the first Incident, and attach any supporting material.</p><div className="mt-3 flex flex-wrap gap-2"><button className={button} onClick={() => onOpenTab?.("parties")}>Add Party</button><button className={button} onClick={onAddIncident}>Add Incident</button><button className={button} onClick={onAddEvidence}>Add Evidence</button><button className={button} onClick={onAddDocument}>Add Document</button></div></div>}
      <Section title="Case Snapshot">
        <div className="mt-3 flex flex-wrap items-baseline justify-between gap-3"><div><div className="text-xl font-semibold text-neutral-950 dark:text-white">{snapshot.name}</div><div className={muted}>{snapshot.category} · {snapshot.status} · {snapshot.folder}</div></div><div className={muted}>Updated {dateLabel(snapshot.lastUpdated)}</div></div>
        <dl className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Active records", snapshot.activeRecordCount],["Archived", snapshot.archivedRecordCount],["Issues", snapshot.issueCount],["Findings", snapshot.findingCount],["Parties", snapshot.partyCount],["Record scope", "Excludes Parties"]].map(([label,value])=><div key={label} className={nested}><dt className="text-xs font-medium text-neutral-500 dark:text-neutral-400">{label}</dt><dd className="mt-1 break-words text-lg font-semibold text-neutral-900 dark:text-neutral-100">{value}</dd></div>)}</dl>
      </Section>
      <div className="grid min-w-0 gap-5 lg:grid-cols-2">
        <Section title="Current Focus"><p className={`mt-3 ${currentFocus.text ? "font-medium text-neutral-900 dark:text-neutral-100" : muted}`}>{currentFocus.text || "No current focus is recorded in the Case Briefing."}</p><dl className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-neutral-500">Actions</dt><dd className="font-semibold dark:text-white">{currentFocus.activeActionCount}</dd></div><div><dt className="text-neutral-500">Reminders</dt><dd className="font-semibold dark:text-white">{currentFocus.reminderCount}</dd></div><div><dt className="text-neutral-500">Deadlines</dt><dd className="font-semibold dark:text-white">{currentFocus.deadlineCount}</dd></div></dl>{currentFocus.topNextAction && <p className={`mt-3 ${muted}`}><span className="font-semibold">Top next action:</span> {currentFocus.topNextAction}</p>}<button type="button" className={`${button} mt-4`} onClick={onOpenFullBriefing}>View full Case Briefing</button></Section>
        <Section title="Needs Attention"><p className={`mt-1 ${muted}`}>{snapshot.findingCount} deterministic case-quality finding{snapshot.findingCount === 1 ? "" : "s"}; showing up to 7.</p>{attentionItems.length ? <ul className="mt-3 space-y-2">{attentionItems.map((item)=><li key={item.id} className={nested}><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0 flex-1"><span className="text-xs font-bold uppercase tracking-wide text-amber-700 dark:text-amber-300">{item.severity} · {item.recordType}</span><h3 className="break-words font-semibold text-neutral-900 dark:text-white">{item.title}</h3><p className={muted}>{item.reason}</p></div><button className={button} onClick={() => act(item)}>Open</button></div></li>)}</ul>:<div className={`${nested} mt-3`}><p className={muted}>No high-priority case-quality findings are currently detected.</p><p className={`${muted} mt-1`}>This does not confirm that the case is factually or legally complete.</p></div>}</Section>
      </div>
      <Section title="Active Issues"><p className={`mt-1 ${muted}`}>Issues are existing flat Sequence Groups; no status, ownership, or hierarchy is inferred.</p>{issues.length ? <ul className="mt-3 grid gap-3 md:grid-cols-2">{issues.map((issue)=><li key={issue.name}><button type="button" onClick={() => onOpenIssue?.(issue.name)} className={`${nested} min-h-24 w-full text-left transition-colors hover:border-lime-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-500`}><span className="block break-words font-semibold text-neutral-950 dark:text-white">{issue.name}</span><span className={`mt-1 block ${muted}`}>{issue.description || (issue.metadataOnly ? "Metadata-only Issue" : "No description recorded")}</span><span className="mt-2 block text-xs text-neutral-500 dark:text-neutral-400">{issue.directRecordCount} direct record{issue.directRecordCount === 1 ? "" : "s"}{Object.entries(issue.counts).length ? ` · ${Object.entries(issue.counts).map(([name,count])=>`${count} ${name}`).join(" · ")}` : ""} · Latest {dateLabel(issue.latestActivity)}{issue.warningCount ? ` · ${issue.warningCount} warning${issue.warningCount === 1 ? "" : "s"}` : ""}</span></button></li>)}</ul>:<div className={`${nested} mt-3`}><p className="font-semibold dark:text-white">No Issues have been created yet.</p><p className={`mt-1 ${muted}`}>Issues group related records into one investigation thread and allow scoped reports and audits.</p><button className={`${button} mt-3`} onClick={() => onOpenIssue?.("")}>Open Issue Manager</button></div>}</Section>
      <div className="grid min-w-0 gap-5 lg:grid-cols-2">
        <Section title="Next Actions"><div className={`${nested} mt-3 border-lime-300 dark:border-lime-700`}><p className="text-xs font-bold uppercase tracking-wide text-lime-800 dark:text-lime-300">Recommended next action</p><h3 className="mt-1 break-words font-semibold dark:text-white">{recommendedAction.title}</h3><p className={muted}>{recommendedAction.reason}</p><button className={`${button} mt-3`} onClick={() => recommendedAction.item ? act(recommendedAction.item) : onOpenTab?.(recommendedAction.tab)}>{recommendedAction.buttonLabel}</button></div>{nextActions.length ? <ul className="mt-3 space-y-2">{nextActions.slice(0,8).map((item)=><li className={nested} key={item.id}><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0 flex-1"><h3 className="break-words font-semibold dark:text-white">{item.title}</h3><p className={muted}>{item.source}{item.issue ? ` · Issue: ${item.issue}` : ""}{item.owner ? ` · ${item.owner}` : ""}</p><p className={`text-sm ${item.dueState === "overdue" ? "font-bold text-red-700 dark:text-red-300" : "text-neutral-600 dark:text-neutral-300"}`}>{item.dueState === "overdue" ? `Overdue · ${dateLabel(item.dueDate)}` : item.dueState === "today" ? "Due today" : item.dueDate ? `Due ${dateLabel(item.dueDate)}` : "No due date recorded"}</p></div><button className={button} onClick={() => act(item)}>Open</button></div></li>)}</ul>:<p className={`${nested} ${muted} mt-3`}>No active actions, due Strategy reviews, or Watch reviews are currently recorded.</p>}</Section>
        <Section title="Recent Activity">{recentActivity.length ? <ul className="mt-3 space-y-2">{recentActivity.map((item)=><li className={nested} key={`${item.recordType}:${item.id}`}><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0 flex-1"><span className="text-xs font-bold uppercase tracking-wide text-neutral-500 dark:text-neutral-400">{item.typeLabel}</span><h3 className="break-words font-semibold dark:text-white">{item.title}</h3><p className={muted}>Updated {dateLabel(item.timestamp)}{item.issue ? ` · Issue: ${item.issue}` : ""}</p></div><button className={button} onClick={() => act(item)}>Open</button></div></li>)}</ul>:<p className={`${nested} ${muted} mt-3`}>No recent record activity is available.</p>}</Section>
      </div>
    </main>
  );
}
